### ISSUE TITLE
Marlin v1.9  DIY servo probe not compile

### ISSUE THREAD

**Issue by qulet** [MarlinFirmware/Configurations#100]
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define Z_ENDSTOP_SERVO_NR 0
#define Z_SERVO_ANGLES {150,10}
#define Z_HOMING_HEIGHT 2
#define Z_CLEARANCE_DEPLOY_PROBE 6
#define Z_CLEARANCE_BETWEEN_PROBES 6
#define Z_MIN_PROBE_REPEATABILITY_TEST
#define AUTO_BED_LEVELING_BILINEAR
#define EXTRAPOLATE_BEYOND_GRID
#define Z_SAFE_HOMING
#define HOMING_FEEDRATE_Z (6*60)
#define SERVO_DELAY { 1000 }
#define DEACTIVATE_SERVOS_AFTER_MOVE
#define NUM_SERVOS 1

#error "Z_ENDSTOP_SERVO_NR is now Z_PROBE_SERVO_NR. Please update your configuration."

**Comment by qulet** [comment]
[Marlin_K_1.9_sonda.zip](https://github.com/MarlinFirmware/Configurations/files/4606745/Marlin_K_1.9_sonda.zip)

**Comment by thisiskeithb** [comment]
The error is telling you exactly what you need to do: Replace `Z_ENDSTOP_SERVO_NR` with `Z_PROBE_SERVO_NR` in your config.

**Comment by qulet** [comment]
thisiskeitb

what exactly does that mean
change in value
 #define Z_ENDSTOP_SERVO_NR 1
#define Z_PROBE_SERVO_NR 0
on:
 #define Z_ENDSTOP_SERVO_NR 0
#define Z_PROBE_SERVO_NR 1
gives nothing ...

**Comment by qulet** [comment]
What should the configuration update consist of?

**Comment by thisiskeithb** [comment]
> what exactly does that mean?

It’s been renamed.

Delete the `Z_ENDSTOP_SERVO_NR` variable and put `Z_PROBE_SERVO_NR` in its place.

**Comment by qulet** [comment]
Thank you helped
 compilation was successful !!!!

**Comment by qulet** [comment]
I have one more problem with Marlin 2.0 MKS Sbase V1.3 + RRDSC 12064.
  The LCD menu works, the SD card does not work. SD cable is:
P0.8 to J8-3 P0.7 to J8-2
P0.9 to J8-4 (P0.5 to J8 -4)
P0.27 to J8-5
What should I do to make the SD card work ????

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
