### ISSUE TITLE
[BUG] Manual Probing Causes Bed to Continuously Rise and Crash into Nozzle on Ender 5 Plus without BL Touch

### ISSUE THREAD

**Issue by itsmaxjeffrey** [MarlinFirmware/Configurations#1002]
**Bug Description:**
After switching from BLTouch to manual probing in the Marlin configuration for an Ender 5 Plus, the printer bed continuously rises during the homing process, leading to a collision with the nozzle. This behavior persists despite the BLTouch being disabled and Auto Bed Leveling (ABL) turned off in the configuration. The BLTouch device has also been physically disconnected from the board.

**Configuration Files:**

[Marlin.zip](https://github.com/MarlinFirmware/Configurations/files/13926092/Marlin.zip)

**Modifications**:

Disabled BLTouch and Auto Bed Leveling in configuration files.
Configured stepper drivers to TMC2208 to accommodate the Creality Silent Board 2.2.
Steps to Reproduce:

Disable BLTouch and enable Manual Probing in the Marlin configuration files for the Ender 5 Plus.
Power on the printer and initiate the Homing process.
Expected Behavior:
The printer should home correctly, stopping at Z=0 without causing a collision, and allow manual bed leveling.

**Actual Behavior:**
The bed continuously moves upwards during homing, resulting in a collision with the nozzle. The movement does not cease unless the printer is powered off manually.

**Additional Information:**

The issue persists even after confirming the correct disconnection of BLTouch hardware.

- I have been using this version of Marlin:
https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Creality/Ender-5%20Plus/CrealityV1%20(RELOADED%20UI)

Please let me know if I should include something else. 

I also commented these out, because they didn't let me compile:

lines 3987-3988

  // #elif !HAS_BED_PROBE
  //   #error "DGUS_LCD_UI RELOADED requires a bed probe."
  lines 3993-3994

  // #elif DISABLED(BABYSTEP_ZPROBE_OFFSET)
  //   #error "DGUS_LCD_UI RELOADED requires BABYSTEP_ZPROBE_OFFSET."
  

I would appreciate any help with sorting this problem. My BL touch is broken and it's gonna take some time until I get a new one... In the meantime, my only option (and goal) is to do manual probing. Currently, there is no method or firmware for Ender 5 Plus **Without BL Tocuh**. 
Thank you for reading

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
