### ISSUE TITLE
[BUG] (i can't config A4982 stepper drivers in MKS BASE V1.6

### ISSUE THREAD

**Issue by MohamedHewela** [MarlinFirmware/Configurations#1029]
![Capture](https://github.com/MarlinFirmware/Configurations/assets/52082544/6dc55ffb-3854-4be1-bffb-48eb7b7e3aba)

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
Use A4988 like you've configured in that screenshot.
