### ISSUE TITLE
[BUG] (short description) need a configuration for 2.1.x bug fix for anycubic chiron with BTT SKR3EZ and BTT TFT35

### ISSUE THREAD

**Issue by slingshott1** [MarlinFirmware/Configurations#1041]
everytime i try and use the current config example for the chiron i get error message to open folder with 2.1.x its already open

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by slingshott1** [comment]
My apologies I'm new to this. Hope you have a great weekend.
