### ISSUE TITLE
Compile error SDSUPPORT Artillery Ruby

### ISSUE THREAD

**Issue by pmanzionna** [MarlinFirmware/Configurations#1059]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

![Cattura](https://github.com/MarlinFirmware/Marlin/assets/171235598/b08a1251-311f-48a9-ae05-03835ebae719)

### Bug Timeline

New bug with Marlin 2.1.2.3

### Expected behavior

Compile error

### Version of Marlin Firmware

2.1.2.3

### Printer model

Artillry Hornet

### Electronics

Artillery_ruby

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by pmanzionna** [comment]
official config/examples/Artillery/Hornet files

**Comment by ellensp** [comment]
this is a bug in the configs

#elif SDSUPPORT should be #elif ENABLED(SDSUPPORT)

**Comment by pmanzionna** [comment]
Thank you ellensp... it works!

**Comment by ellensp** [comment]
I think it was meant to be #elif HAS_MEDIA  but that needs testing

**Comment by pmanzionna** [comment]
Tested with #elif HAS_MEDIA... it seems to work.

**Comment by thisiskeithb** [comment]
I opened a PR with fixes in https://github.com/MarlinFirmware/Configurations/pull/1060, but thinkyhead directly committed them instead of merging my PR so this issue was not auto-closed.

Closing as resolved.
