### ISSUE TITLE
Temperature is showing without any thermistor.

### ISSUE THREAD

**Issue by Champ7120** [MarlinFirmware/Configurations#1067]
### Bug Description

Hot end temperature is showing without any thermistor. Attached photo is self explanatory. I'm using Mega2560 (Mega WiFi R3 Atmega2560 NodeMCU ESP8266 32Mb Memory USB-TTL CH340G) + Ramps 1.4 combination with Marlin-2.1.x. I have replaced ramps 1.4 to 1.6 and tried again. However, still it showing temperature. Further, i tried different pin i.e 15, then it worked fine for ramps 1.4 & 1.6. But it is showing 58°C / 73°C with pin 13 & 14 respectively.
 

**Expected behavior:**

"err" to be shown when there is no thermistor.

**Actual behavior:**

73°C showing without any thermistor.

[Marlin.zip](https://github.com/user-attachments/files/15903561/Marlin.zip)
![IMG_6398](https://github.com/MarlinFirmware/Configurations/assets/173282337/8560bc77-dd38-4c39-9efa-a56ddadbcc4f)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
