### ISSUE TITLE
unable to access sm32 board download

### ISSUE THREAD

**Issue by soapy75** [MarlinFirmware/Configurations#1076]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I am attempting to install firmware on malyan m200,

I have pasted the board url and have checked the box required, but searching for malyan or sm32 in the board manager shows no results. I have reinstalled arduino ide

### Bug Timeline

new

### Expected behavior

show a download button

### Actual behavior

no result

![image](https://github.com/MarlinFirmware/Configurations/assets/68105703/696f28f2-6ad6-4b24-8cb1-f7ea9f745f85)

### Steps to Reproduce

1. download ide
2. check the box
3. paste board manager url
4. search for the board in board manager

### Version of Marlin Firmware

N/A

### Printer model

malyan m200

### Electronics

stock

### LCD/Controller

N/a

### Other add-ons

none

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

![image](https://github.com/MarlinFirmware/Configurations/assets/68105703/fe0e9ea5-5974-4b88-8650-e480ee99cff5)

**Comment by thisiskeithb** [comment]
Building in Arduino IDE doesn’t work, but should in PlatformIO: 
- https://github.com/MarlinFirmware/Configurations/issues/900
