### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by 7u5a** [MarlinFirmware/Configurations#1113]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I only see the wanted temprature I beleive?
![462763917_10162124114949255_4675345452235032871_n](https://github.com/user-attachments/assets/6637e10b-269d-46fd-bebd-2a26ee57dd95)

### Bug Timeline

I don't know, never tried Marlin before...

### Expected behavior

Back in the old software on my old board I could se the wanted temprature and the actual.

### Actual behavior

I only see 1 temprature, the other is 0 when warmin up and so on

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

CR-10S

### LCD/Controller

BIGTREETECH TFT35-E3 V3.0.1 Display Touch Screen/BigTreeTech SKR Mini E3 V3.0 32 Bit

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration_adv.zip](https://github.com/user-attachments/files/17351159/Configuration_adv.zip)

**Comment by ellensp** [comment]
see first icon. T0  22/0

This is the hotend temperature  22 degrees C and it is currently not set to heat up, ie 0

With this display there is a lot of things you need to enable in Marlin for it to display the correct information.

See the list from bigtreetech https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware?tab=readme-ov-file#marlin-dependencies

Please note this is not a support forum

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
