### ISSUE TITLE
Ender-5 S1 Multilanguage Error

### ISSUE THREAD

**Issue by samuraijakk** [MarlinFirmware/Configurations#1123]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Using bugfix-2.1.x, compiling firmware for the Ender-5 S1 results in an error (as shown in the picture linked below). The issue is resolved by removing line 2745 in configuration.h "#define LCD_LANGUAGE zh_CN" leaving just the single language line of "#define LCD_LANGUAGE en". I was able to successfully compile my firmware after deleting that line.

![image](https://github.com/user-attachments/assets/23a8d69c-9ac4-415f-81c3-8e4d23b3956f)
![image](https://github.com/user-attachments/assets/6af0f3d9-e851-4c75-aab7-a38242bcc29a)
[Configurations.zip](https://github.com/user-attachments/files/18271054/Configurations.zip)

### Bug Timeline

It's my first time compiling firmware, so it's new as far as I know.

### Expected behavior

I expected the firmware to compile successfully prior to making the edit.

### Actual behavior

I was unable to successfully compile the firmware until I removed that line.

### Steps to Reproduce

Compile the firmware as it is, downloaded from github via the bugfix-2.1.x version for the Ender-5 S1

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Ender-5 s1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by thisiskeithb** [comment]
The Ender-5 S1 is still a work in progress and not supported:
- https://github.com/MarlinFirmware/Marlin/pull/25382
