### ISSUE TITLE
Creality Ender 5 Plus

### ISSUE THREAD

**Issue by Cheo7811** [MarlinFirmware/Configurations#12]
There are example configuration for Ender 5 and 5 Pro but not for 5 Plus

**Comment by thisiskeithb** [comment]
The 5 Plus uses a TFT that’s not currently supported in `bugfix-2.0.x`.

**Comment by flub9** [comment]
This appears to be resolved now @Cheo7811. Path: config/examples/Creality/Ender-5_Plus

**Comment by Cheo7811** [comment]
Thank you flub9
