### ISSUE TITLE
Ender-3 Pro: Configuration_adv.h failed

### ISSUE THREAD

**Issue by TomMeyer90** [MarlinFirmware/Configurations#133]
error compiling Ender 3 Pro Configuration_adh.h

**Comment by TomMeyer90** [comment]
![grafik](https://user-images.githubusercontent.com/67189937/85200820-c848be00-b2fa-11ea-9e77-b3075d0f369a.png)

**Comment by thinkyhead** [comment]
You are using an older Marlin source code with a newer Marlin config.
