### ISSUE TITLE
Ender 3 v2 (5 pin BLTouch Port)

### ISSUE THREAD

**Issue by fleek** [MarlinFirmware/Configurations#151]
Hi.

Are there any circuit diagrams of the main board for Ender 3 V2?  I would like to ask what are the port numbers on the mainboard for the special 5 pin bLTouch port.  I would like to offer this configuration for the 5 pin BLTouch port if possible.

**Comment by thinkyhead** [comment]
No one has this information yet except for Creality3D. But you can use `PINS_DEBUGGING` and the `M43` command to test each pin and get its DIO number.
