### ISSUE TITLE
Remove Check for If HAS_SDCARD_CONNECTION

### ISSUE THREAD

**Issue by diabl0w** [MarlinFirmware/Configurations#172]
https://github.com/MarlinFirmware/Configurations/blob/bb29dafbd0046a88389541203c5b98a3800a4fe0/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%201.2/Configuration_adv.h#L1283

This is no longer used by Marlin, just remove the if check and keep the SDCARD_CONNECTION definition of whether it is LCD or ONBOARD

I solved this after not understanding why my SDCARD wasnt detected even after changing to ONBOARD. It was because the IF check failed so it just stayed to the default LCD value

**Comment by thisiskeithb** [comment]
Thanks for the heads up! I've put in https://github.com/MarlinFirmware/Configurations/pull/174 to address this.
