### ISSUE TITLE
Platform IO Compile with class U8GLIB_ST7920_xxxx

### ISSUE THREAD

**Issue by SG-Viper2020** [MarlinFirmware/Configurations#188]
Hi there.
Lately recompile my current version after change some setting on the endstop.
This version was working fine ( 2.0.6 ) where the Arduino IDE failed to compile, so i move into Platform IO.
Everything was working after i updated it and also now seeing below messages that not able to solve.
Help needed here....
By the way, i have tried use the new and old and also different version of the u8glib after seeing some commented it will resolve, but not for me..

'class U8GLIB_ST7920_128X64_RRD' has no member named 'print'

u8g.print(i) line on the lcdprint_u8g.cpp and lcdprint_u8g.cpp

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
