### ISSUE TITLE
Status/plans of this repository

### ISSUE THREAD

**Issue by bojanpotocnik** [MarlinFirmware/Configurations#2]
When I first saw this repository I thought that the `MarlinFirmware/Marlin/config/examples` directory will be removed at the expense of this repository used for that purpose; or that `Marlin/config` will  be a git-submodule of `MarlinFirmware/Configurations` and then each user will checkout the desired submodule branch; or .... .

It seems, however, that this repository is not actively maintained, neither are the configuration files correct (looking in some directories all the Configuration.h are just copies of the default).

What are the plans if this repo? I suppose we shall use the files in `MarlinFirmware/Marlin/config/examples` until further notice?

**Comment by Dakkaron** [comment]
I reckon you are on 1.9.x? On the 2.0.x the example configuration folder has been removed already.

**Comment by RudyBenner** [comment]
It has been moved, not removed.
C:\Users\RudolfBenner\Documents\GitHub\Marlin\config

**Comment by Dakkaron** [comment]
Thanks for correcting that, I didn't see that.

**Comment by RudyBenner** [comment]
Can you close?

**Comment by Dakkaron** [comment]
The original question wasn't answered.

**Comment by bojanpotocnik** [comment]
As RudyBenner already noted, I am talking about `bugfix-2.0.x` where the `Marlin/config/examples/` directory is updated almost daily, in contrast to this repo which is not updated at all (the only 4 commits are the Initial commit, Import of configs and two README updates).

This idea of having the separate repository is good, but I am also aware that it is harder to realize it - to migrate the existing structure to this new layout. That's why I am wondering, what are the plans? Is this some afternoon idea with the lowest priority among Marlin contributors, is someone already actively working on, is there any help required, ...?

**Comment by thisiskeithb** [comment]
Check out https://github.com/MarlinFirmware/Marlin/commit/7b304cee16bf87962eba998d8c293e5d4bd23c71. Configs have been moved here 🙂
