### ISSUE TITLE
Anycubic kossel delta plus + tmc2130 standalone

### ISSUE THREAD

**Issue by pablopeu** [MarlinFirmware/Configurations#20]
I'm using 2.0bugfix from December with no problems (attached configs), tried to upgrade to 2.03 stable and its not working, tried downloading todays (17-2-20) bugfix release and the problem remains. Attached are the config files

The problem is: X axis doesn't move, 

From the examples I only defined the bare minimum:

in configuration.h:
defined the printer as plus model
probe as 2
heated bed as 1
drivers as tmc2130_standalone (extruder is default 4988)

in configuration_adv.h:
#define USE_CONTROLLER_FAN
#define CONTROLLER_FAN_PIN 7  

What could be wrong?
Thanks

[2-17-20- anycubic delta plus.zip](https://github.com/MarlinFirmware/Configurations/files/4214560/2-17-20-.anycubic.delta.plus.zip)
[This one works fine.zip](https://github.com/MarlinFirmware/Configurations/files/4214571/This.one.works.fine.zip)
@thinkyhead

**Comment by thinkyhead** [comment]
If this is still an issue with Marlin 2.0.5 then please post a complete issue over on the MarlinFirmware/Marlin issue queue.
