### ISSUE TITLE
CDC serial issue with config/examples/delta/MKS/SBASE/Configuration.h

### ISSUE THREAD

**Issue by ellensp** [MarlinFirmware/Configurations#212]
In config/examples/delta/MKS/SBASE/Configuration.h is
```
#define SERIAL_PORT 0

/**
 * Select a secondary serial port on the board to use for communication with the host.
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
//#define SERIAL_PORT_2 -1
```
Ie CDC serial over USB is disabled.
Suspect this generic config should be 
#define SERIAL_PORT -1  

Seems to be present in bugfix-2.0.x,import-2.0.x and release-2.0.6.1 (and probably more, I didn't go further back) 

<strike>I don't know the procedure to make a PR for this change since I believe some of these are auto generated.</strike>

Raised by issue https://github.com/MarlinFirmware/Marlin/issues/19334

Edit: PR added.

**Comment by thisiskeithb** [comment]
Target PRs against `import-2.0.x` and thinkyhead will work his magic.

**Comment by ellensp** [comment]
@thisiskeithb  Thanks for this info.  I was just looking at some of your PR's and had arrived at same conclusion.
