### ISSUE TITLE
Allen key probe compile error "You can't home to a z min endstop with a Z_PROBE_ALLEN_KEY."

### ISSUE THREAD

**Issue by yankee14** [MarlinFirmware/Configurations#217]
My [Configuration.h](https://gist.github.com/yankee14/e738ff03ac2fa38e093668fbf57fabb0) for reference.

I am playing around with making an allen key probe for my Ender 3 V1, but hit an error I'm a little confused about when compiling. I have wired a limit switch in series with my Z limit switch. I confirmed that everything is fine electrically because I can successfully home the printer with the switch in series. The error I get is:

```
In file included from sketch/src/HAL/DUE/fastio/../../../inc/MarlinConfig.h:41:0,
                 from sketch/src/HAL/DUE/fastio/G2_PWM.cpp:43:
sketch/src/HAL/DUE/fastio/../../../inc/SanityCheck.h:1570:4: error: #error "You can't home to a z min endstop with a Z_PROBE_ALLEN_KEY."
   #error "You can't home to a z min endstop with a Z_PROBE_ALLEN_KEY."
    ^~~~~
```
I have looked at the suggested [Delta configuration](https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/delta/generic/Configuration.h#L1043) as suggested in the configuration source file, and the way it is [written in the Marlin source](https://github.com/MarlinFirmware/Marlin/blob/9ade72aee94981b26be0ca125ab487166d0bd7e3/Marlin/src/module/probe.cpp#L159). I'm not sure if this is appropriate, since I plan on manually deploying and stowing the allen key with the probe pause functions elsewhere in the firmware.

Would someone be able to give suggestions about where I can look next?

![signal-2020-09-17-185420](https://user-images.githubusercontent.com/12487802/93539734-3f501b80-f917-11ea-806c-8cb9c672e2aa.jpeg)

**Comment by thinkyhead** [comment]
Did you find the answer you were looking for?

**Comment by yankee14** [comment]
@thinkyhead Unfortunately no, not yet.

**Comment by thinkyhead** [comment]
If your machine is not a DELTA then simply comment out the `#error` line and carry on. The allen key probe is not supported for use on a non-delta machine, but you can probably ignore that.

**Comment by yankee14** [comment]
@thinkyhead ah okay. I'll give it a shot, thanks
