### ISSUE TITLE
Unable to compile for either of my printers.

### ISSUE THREAD

**Issue by Wick3dJack** [MarlinFirmware/Configurations#219]
I got both of my SKR Pro V1.1 &1.2 with TMC2209's and a TFT3.5 V2.0 back in May & have yet been able to use either of them. 
The V1.1 is for the Chiron & V1.2 and TFT are for my Artillery Sidewinder X1 I've gone as far as buying a entire new pc thinking it was my 15yr old pc but now thats I've upgraded the problem is still there..
I'm trying to configure the latest Marlin 2.0 bugfix for the Chiron using all TMC2209 steppers (still using the endstops) with the stock TFT No bed sensor and possibly a esp-01s for wifi if thats possible. I have no idea why but if I change 1 line to enable say the tft I get 5 more errors that pop up stating the tft needs sensor for homing needs babystepping needs all this other crap enabled & once all done I get even more errors.. In 5 months I have NOT successfully compiled one firmware file & about to toss all this stuff in the trash & give up.
Could someone please lend a hand & if this isnt in the correct spot I'm sorry I'm not even sure how to use this site either..
Thank You

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
