### ISSUE TITLE
Default Ender 3/Pro/V2 Configuration Suggestion

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Configurations#220]
Not sure if this is widespread, but my Ender 3 Pro's z-axis always falls once its deactivated at idle. Causes a bunch of problems regarding scratching of the bed surface. I think that the default value for Z timeout should be set to the following:
#define DISABLE_INACTIVE_Z false

But only if its known that most if not all ender 3 z axes fall.

**Comment by thisiskeithb** [comment]
The Ender-3's x gantry shouldn't fall on it's own, but can if your eccentric nuts aren't adjusted properly, or running a heavy direct drive setup.

**Comment by ghost** [comment]
ah gotcha. so its just me then. thanks!
