### ISSUE TITLE
Problem trying to install marlin on MSK-SGEN_L V1.0

### ISSUE THREAD

**Issue by mechanicmem** [MarlinFirmware/Configurations#229]
So, i'm very new at this, but i'm trying to install marlin on a MKS-SGEN_L V1.0 Board, however, after uploading the firmaware, i cant get anything from the lcd, actually i do see some strange symbols on the lcd if i move the button a bit
![WhatsApp Image 2020-09-29 at 17 12 28](https://user-images.githubusercontent.com/16451129/94610722-1749ac00-0277-11eb-8db5-bff2c6beb6fd.jpeg)

i already tried to enable MKS_LCD12864 and MKS_MINI_12864 on config but the problem persists, thank you in advance

**Comment by thinkyhead** [comment]
https://marlinfw.org/docs/basics/troubleshooting.html
