### ISSUE TITLE
Wouldn't it be better to store custom configurations in another format?

### ISSUE THREAD

**Issue by mgcrea** [MarlinFirmware/Configurations#230]
Patching marlin configuration and keeping up with changes is quite painful. I guess it must have been discussed before but wouldn't it be better to store at least a git `.diff` file along the actual files? Would be so much quicker to pick and apply patches.

Would be great to keep per config versions (stored like `diffs/Configuration.h_v020007.diff`) to allow people stuck on legacy marlin version to easily get a working config.

Ideally the best would be to switch to some `.yaml` like config file with some kind of preprocessor that would generate the git diff file for you.

Example of diff file:

```diff
diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
index dec1a81be..d8a04492a 100644
--- a/Marlin/Configuration.h
+++ b/Marlin/Configuration.h
@@ -1,3 +1,5 @@
+#include "./Configuration_delta.h"
+
 /**
  * Marlin 3D Printer Firmware
  * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
@@ -70,7 +72,7 @@
 // @section info
 
 // Author info of this build printed to the host during boot and M115
-#define STRING_CONFIG_H_AUTHOR "(none, default config)" // Who made the changes.
+#define STRING_CONFIG_H_AUTHOR "(mgcrea, Q5 config)" // Who made the changes.
 //#define CUSTOM_VERSION_FILE Version.h // Path from the root directory (no quotes)
 
 /**
@@ -103,13 +105,13 @@
  *
  * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
  */
-#define SERIAL_PORT 0
+#define SERIAL_PORT 3
 
 /**
  * Select a secondary serial port on the board to use for communication with the host.
  * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
  */
-//#define SERIAL_PORT_2 -1
+#define SERIAL_PORT_2 1
```

**Comment by thinkyhead** [comment]
With Marlin stored in GitHub, a "patch" file can be easily generated between any two sets of Marlin configurations and then that patch can be applied to an edited set of configuration files to get those changes applied, just as you will get from a common Git merge. You still have to deal with merge conflicts when applying the patch, and depending on your merge tool this may be tricky.

So as time allows, we are putting our efforts into tools that can parse the configurations, provide a proper user interface, and make the settings more portable between versions within that interface. See the "Auto Build Marlin" project for details.
