### ISSUE TITLE
Hotend temperature show negative target values

### ISSUE THREAD

**Issue by wernju1** [MarlinFirmware/Configurations#233]
Anycubic I3 mega / trigorilla board
Hotend temp. Shows negative target values.
e.g. preheat temp should 195° / display -67°

**Comment by mytja** [comment]
Check the wiring!
If the temperature sensor is not in contact with motherboard, then it might give out strange values

**Comment by wernju1** [comment]
With 2.0.6.1 and previous releases it works fine

**Comment by wernju1** [comment]
The temperature while heating the hotend seems not to be affected and is displayed correctly.
What i mean is the target temperature, e.g. 180° for pla or 230° for abs.
These values are not displayed correct, therefore negative values were shown at the display instead.

**Comment by mytja** [comment]
Hmmmmm. I'm out of ideas, maybe @thinkyhead knows the answer...

**Comment by wernju1** [comment]
Problem is fixed with PR #19572

**Comment by mytja** [comment]
Then okay...

**Comment by ellensp** [comment]
@wernju1 Then perhaps you could close this issue?

**Comment by wernju1** [comment]
Sorry, I
