### ISSUE TITLE
Skr 1.3 + TMC2130 + TFT35 v2 - Steppers do not work

### ISSUE THREAD

**Issue by mxmxx93** [MarlinFirmware/Configurations#24]
Hi everyone, 

first of all I wanted to apologize if there are errors in the post but I'm new, I used the search button but nothing about this configuration.

My configuration is the one mentioned in the title. My problem is that once I launch the command (both from pc and TFT) to move the steppers they do not respond and do not move.

I tried to mount several Firmware from 2.0.0 to 2.0.4, but the problem remains the same. I followed the guide ( link ) to set the firmware and everything, but the result was always negative. 

if you need any more information, I will gladly provide it, I would be very grateful. Unfortunately, my printer is OFF since Christmas for this reason... and now I'm giving up and thinking of giving up

**Comment by DaSTIG** [comment]
I would start by enabling TMC_Debug in firmware, and getting the  stepper drivers status with M122.  If you have the firmware not configured correctly, they arent going to move.   I been using the SKR 1.3 with 2130s for 8 months, and they work great.

**Comment by oldman4U** [comment]
Hi.

Has the printer ever worked before and what changed then?
Could you attach some pictures of the mainboard and the drivers and some more information about the mode you are using.

The (link) does not work.

**Comment by thinkyhead** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) to the main project.
