### ISSUE TITLE
Ender 3 V2 Changes not showing after flash

### ISSUE THREAD

**Issue by lhartman89** [MarlinFirmware/Configurations#241]
![20201004_150451](https://user-images.githubusercontent.com/22782362/95024749-205dc300-0653-11eb-86c7-e360cac83e3f.jpg)
![Screenshot (6)](https://user-images.githubusercontent.com/22782362/95024661-9a417c80-0652-11eb-9076-45ab8ab9e834.png)
I compiled my firmware and successfully updated my Ender 3 V2. I enabled mesh bed level and changed the ABS preheat name to PETG as well as change the X and Y dimensions to 235mm and enabled PID Bed autotune and none of this is showing up. I also flashed the display with the DWIN_SET file. Am I doing something wrong?

**Comment by thinkyhead** [comment]
Creality has not implemented those elements in their DWIN code for the LCD. Work is underway to bring the full MarlinUI to this display, as time allows.
