### ISSUE TITLE
No creality Cr10 s4 configuration

### ISSUE THREAD

**Issue by arthurmaffre** [MarlinFirmware/Configurations#242]
There is no configuration for the creality Cr 10 s4, good idea to add it.

**Comment by Gamester17** [comment]
@Arthurmaffre34 please see PR #245 for CR-10 S4 config example (based on CR-10 S5 config example), please feel free to test.

**Comment by arthurmaffre** [comment]
Ok thank you

**Comment by ellensp** [comment]
RR 245 is now merged and the configurations for a CR-10 S4 with Creality V1 are now available.
