### ISSUE TITLE
Creality Ender-5 PRO with V4.2.2 board

### ISSUE THREAD

**Issue by ThiagoRangel7** [MarlinFirmware/Configurations#254]
I recently got an Ender-5 Pro that came with a V4.2.2 motherboard. I think the same happened to Ender-3 and Ender-3 Pro.

Problem is that the config files for the Ender-5 Pro only support the former board version (V1.x).

I don't know if I should only change the line `#define MOTHERBOARD BOARD_MELZI_CREALITY` to `#define MOTHERBOARD BOARD_CREALITY_V4`, or if there are other changes I also need to make. I've read that the stepper drivers also changed for silent ones.

Would appreciate any help. Thanks.

**Comment by Gamester17** [comment]
There is a config example for Ender-3 Pro with V4.2.2 board so suggest you mix and match that with Ender-5 Pro and submit PR.

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20Pro%20V1.5

Note that that directory might be moved to "Ender-3 Pro/CrealityV422" pull request #259 is accepted and merged. If so see:

https://github.com/MarlinFirmware/Configurations/tree/patch-11/config/examples/Creality/Ender-3%20Pro/CrealityV422

Anyway, try mixing that with:

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-5%20Pro/Creality

I guess however that directory will be renamed to "CrealityV1" if #260 is accepted and merged. If so see:

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-5%20Pro/CrealityV1

Highly suggest that you submit a pull request as a contribution once done to that other can benifit for such an example file too.
