### ISSUE TITLE
Ender 3 with 4.2.7 TMC2225

### ISSUE THREAD

**Issue by wintxilin** [MarlinFirmware/Configurations#264]
I own an Ender 3 (the first one), and to make it silent, I bought the 4.2.7 motherboard with the TMC2225 drivers but it came with Marlin 0.0.6 
I tried it and got it running without any problems and basically zero sound, I was very pleased with it, but since the Marlin was old I updated it to the newer version Marlin 2.0.7.1 I had some issues but finally I got it working, and I have been printing a couple of things succesfully, but I noticed that I now can hear the motors when before I couldn't.... so I have made an upgrade that made me have more noise than before coming out of the printer. 
I thought about checking the drivers so I checked at the VSC and I saw that the active drivers are the TMC 2208. My previous drivers where the TMC2225 and where silent, i'm guessing that the problem is there?

Not sure if i'm doing something wrong, or there is no support for those drivers, or there is something else going on.... 
Someone may help?

**Comment by chepo92** [comment]
This is no for support, close issue and please post in the forums/discord/support groups

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
