### ISSUE TITLE
Possible Typo Bug

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Configurations#280]
Within Ender 3 Pro V1.5 Config Configuration_adv.h

There is a line that starts with:
#IF IS_ULTIPANEL

This line fails to compile. Changing this to 

#IF ENABLED(IS_ULTIPANEL) 

works however. Is this the correction line?

**Comment by cstueckrath** [comment]
duplicate of #272

**Comment by ghost** [comment]
Ah yes. I didn't see that my apologies. But can confirm using the changes above fixes the problem.
