### ISSUE TITLE
CR-10 BIGTREETECH-SKR-mini-E3-master 2.0

### ISSUE THREAD

**Issue by mbump314** [MarlinFirmware/Configurations#297]
I have been unable to compile correct Firmware to get printer to work. Homing is broke. When you try to auto home the motors slam into the limits and do not stop. I can jog the motors and they seem to work, but nothing else will work from screen. 

Any help will be appreciated.

**Comment by thisiskeithb** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
