### ISSUE TITLE
ball pathway 

### ISSUE THREAD

**Issue by jupando** [MarlinFirmware/Configurations#299]
![image](https://user-images.githubusercontent.com/73614891/97493463-bed40000-1943-11eb-95ac-7e675d3d8fe0.jpg)
hey so i just made a little pathway for my circle/ ball to go through but the one thing that’s wrong with it it’s that when it reaches the end, the ball goes up and down way to fast. I’ve tried doing the frameRate thingy but it still doesn’t work

**Comment by ManuelMcLure** [comment]
This has absolutely nothing to do with Marlin.

**Comment by jupando** [comment]
> This has absolutely nothing to do with Marlin.

Oh I wrote this in the wrong place sorry.

**Comment by ellensp** [comment]
And yet you still didn't close it?

**Comment by jupando** [comment]
you don’t need to be so rude. It was just a question that could be easily answered. Sorry

**Comment by ellensp** [comment]
This is completely off topic
But yet you refuses to close it. 
It is you sir that is being rude, wasting all of our time.

**Comment by jupando** [comment]
with all due respect, if you noticed that it was off topic why did you respond anyways?? I am not refusing to close it, I tried to and it wouldn’t let me. I am not that stupid and for what reason would I want that to be opened after all?? Oh and it’s it a problem to answer my question anyways? it’s not that hard. Oh and i’m not a “sir” i’m a girl.

**Comment by Vertabreak** [comment]
most of this repo is publicly posted to the marlin discord where 1000's can see it as well as any of the devs of this project this issue should be closed.
