### ISSUE TITLE
Creality Ender 3 with v1.1.5 silent board... which config file to use?

### ISSUE THREAD

**Issue by nick-s-b** [MarlinFirmware/Configurations#318]
Hi,

I'm trying to install Marlin on an Ender 3 but I have an issue with choosing the proper configuration file.  The board I have is a Creality v1.1.5 board and it has an ATmega1284P micro and comes with TMC2208 stepper drivers. The board also came pre-loaded with a bootloader so I didn't have to install it manually.

After combing though example config files, the set that caught my eye is `Ender-3 Pro V1.5` since it references TMC2208 steppers on all the axes. However, that Readme file states:

> This is a surprise upgrade to the Ender 3 Pro that some customers began to receive around mid-July of 2020. No documentation or support page exists for this variant. It appears to be an Ender 3 Pro with the 32-bit Ender 3 V2 board and the stock Ender 3 Pro display. To see which version you have, examine the control board. The newer board is Creality v4.2.2.

v1.1.5 seems to be a different board altogether and seems closer to v1 version of the board but with TMC2208

How should I proceed? Should I use `CrealityV1` config files and then merge in lines referencing TMC2208 from the v15 config? And what to do about PID and temperatures...

Thanks for any guidance! Pic of the board is attached.

![IMG_1752](https://user-images.githubusercontent.com/7957590/98435977-63251780-20a5-11eb-86a9-b79bfc773936.JPG)

**Comment by ellensp** [comment]
Creality loves changing parts on their printers without telling anyone or changing the name...

Yes use  CrealityV1 config and set X,Y,Z and E stepper drivers to TMC2208_STANDALONE
