### ISSUE TITLE
 Marlin configurations 

### ISSUE THREAD

**Issue by scatterbomb** [MarlinFirmware/Configurations#323]
BigTreeTech SKR v1.3 configuration files missing for the ender5 & other Creality models..

**Comment by ellensp** [comment]
Not all combinations of Controller and Printer exist. These are all created manually, by people volunteering their time and their configs.

**Comment by ellensp** [comment]
In this case Ender 5 configs exist for BigTreeTech SKR 1.4 Turbo (TMC2209), you literally have to change one line 
#define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO to  #define MOTHERBOARD BOARD_BTT_SKR_V1_3 and your done.
