### ISSUE TITLE
Problemi di auto livellamento

### ISSUE THREAD

**Issue by RaffaelB** [MarlinFirmware/Configurations#326]
Buona sera a tutti, ho da poco realizzato una stampante Corexy, con Marlin 1.1.8, estratto dalla Tronxy X5SA, meccanica ok elettronica Arduino Mega e Ramps 1.4, il tutto funziona egregiamente, unico problema (x me non piccolo) è il livellamento del piatto, un 300x300, ho installato il sensore di prossimità, che mi fà anche l'homing, e funziona bene, il processo di livellamento va a buon fine, ho verificato che memorizza i dati nella eprom, ma di fatto, quando va in stampa, sembra non tenerne conto.
Ho inserito nel gcode anche il comando M420 S1 dopo il G28, ma non ho notato variazioni. avrei bisogno di aiuto da qualcuno di voi, più sgamato di me.
Grazie in anticipo x le vostre risposte.
Good evening everyone, I have recently made a Corexy printer, with Marlin 1.1.8, extracted from the Tronxy X5SA, mechanics ok electronic Arduino Mega and Ramps 1.4, everything works very well, only problem (for me not small) is the leveling of the flat, a 300x300, I installed the proximity sensor, which also makes me homing, and it works well, the leveling process is successful, I verified that it stores the data in the eprom, but in fact, when it goes to print , seems not to take this into account.
I also entered the M420 S1 command after the G28 in the gcode, but I didn't notice any changes. I would need help from some of you, more sgam than me.
Thanks in advance for your answers.

**Comment by ellensp** [comment]
Sorry this is not a support forum.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
