### ISSUE TITLE
Unable to Invert Stepper direction

### ISSUE THREAD

**Issue by phil1horton** [MarlinFirmware/Configurations#340]
Switched out the extruder stepper for my Tevo Nereus with a Makerbase MKS Nano 1.1 mainboard. The original stepper has one gear that drives another gear to moves the filament. I switched it to a stepper that drives the filament directly and went into the following field to switch the direction and nothing changes.

// @section extruder

// For direct drive extruder v9 set to true, for geared extruder set to false.
#define INVERT_E0_DIR true
#define INVERT_E1_DIR false
#define INVERT_E2_DIR false
#define INVERT_E3_DIR false
#define INVERT_E4_DIR false
#define INVERT_E5_DIR false
#define INVERT_E6_DIR false
#define INVERT_E7_DIR false

**Comment by ellensp** [comment]
This is normally a pin conflict, something else on the dir pin you have enabled.  

 For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by phil1horton** [comment]
If I change the config and it does not change the board, isn’t that a Marlin firmware issue? And not a board issue?
