### ISSUE TITLE
Problem with "waiting for filament change" at the beginning of printing

### ISSUE THREAD

**Issue by silelis** [MarlinFirmware/Configurations#342]
Hello,

My firmware is 2.0.7.2 uploaded to Creality CR20 with BL Touch and runout sensor.

I have strange printer behavior where at the very beginning printer gives notice about "waiting for filament change". See movie bellow (almost end of the movie):
https://www.youtube.com/watch?v=P5A8Bq4j36U&feature

The printed file and configs in atachement. Printed file had worked proparely before i changed firmware.
[Congifs and printed file.zip](https://github.com/MarlinFirmware/Configurations/files/5588521/Congifs.and.printed.file.zip)

**Comment by ellensp** [comment]
This is very likely a configuration issue and not a Marlin bug.
Come to the Discord for support, If we can't solve the issue there, then we can reopen this as a actual bug.  

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
