### ISSUE TITLE
Longer LK4 Pro

### ISSUE THREAD

**Issue by Cyberyoryo** [MarlinFirmware/Configurations#344]
Longer LK4 Pro con un E3D V6 y un extrusor bondtech clone.

**Comment by ellensp** [comment]
"Longer LK4 Pro with an E3D V6 and a bondtech clone extruder."  
I'm guessing this is a request for Config files for this particular Combination?

We mostly only provide Configuration files for Machines with Stock Hardware (with the exception of commonly used upgrade motherboards)

From what I can find the LK4 Pro is just an Alfawise U30 Pro, and we don't have any configs for that machine.  

Supongo que esta es una solicitud de archivos de configuración para esta combinación en particular.

En su mayoría, solo proporcionamos archivos de configuración para máquinas con hardware de stock (con la excepción de las placas base de actualización de uso común)

Por lo que puedo encontrar, el LK4 Pro es solo un Alfawise U30 Pro, y no tenemos ninguna configuración para esa máquina.
