### ISSUE TITLE
Configuration for CR-20 Pro whit SuperSilent V4.2.7

### ISSUE THREAD

**Issue by Ixso88** [MarlinFirmware/Configurations#345]
Salve,

ho una CR-20 Pro ed ho appena acquistato una Board V4.2.7, configurata e funzionante, l'unico problema rimane il display, non riesco a capire come settarlo. I pin li ho sia della Board che del Display ma tentando continuo ad avere problemi con le librerie U8G.

Cordialmente
Giuseppe

Hello,

I have a CR-20 Pro and I just bought a Board V4.2.7, configured and working, the only problem is the display, I can't figure out how to set it. I have the pins both of the Board and of the Display but trying to keep having problems with the U8G libraries.

with regard

**Comment by ellensp** [comment]
This is not a general support forum.
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
