### ISSUE TITLE
CR6 SE example configurations - Unknown MOTHERBOARD value set in Configuration.h

### ISSUE THREAD

**Issue by CRCinAU** [MarlinFirmware/Configurations#350]
When trying to build against the example configurations here:
https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/CR-6%20SE

The build fails with:
```
Unknown MOTHERBOARD value set in Configuration.h
```
The source for the build is todays bugfix-2.0.x checkout.

Is this simply the wrong value, or is something missing?

**Comment by ellensp** [comment]
This motherboard is still a work in progress 
https://github.com/MarlinFirmware/Marlin/pull/19958
Has not been committed yet.
GIve it a few days.
