### ISSUE TITLE
[BUG] Example import-2.0.x/config/examples/delta/Tevo Little Monster wrong board defined

### ISSUE THREAD

**Issue by lemmingDev** [MarlinFirmware/Configurations#354]
### Bug Description

The the example configuration for Tevo Little Monster, the MOTHERBOARD is defined as BOARD_MKS_GEN_L

The motherboard that comes with all Tevo Little Monsters is the MKS SBase, so the definition should be BOARD_MKS_SBASE

### My Configurations

[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5279144/Configs.zip)

### Steps to Reproduce

1. Use the provided Tevo Little Monster Configuration.h and Configuration_adv.h files

**Expected behavior:** [What you expect to happen]
#define MOTHERBOARD BOARD_MKS_SBASE

**Actual behavior:** [What actually happens]
#define MOTHERBOARD BOARD_MKS_GEN_L

#### Additional Information
There could be other changes needed as well,

**Comment by thinkyhead** [comment]
There are now V1 and V2 Tornado configs. Shouldn't be hard to add a V3 there and two more versions for the little monster too.

**Comment by lemmingDev** [comment]
> @lemmingDev I attempted to update this for you, but I am not comfortable with the changes I have to make, without having the printer to test it.
> 
> Do you have a working configuration for a stock Little Monster?
> 
> The details that I am unsure about:
> 
> * Microsteps? 32 or 64? (And the steps/mm derived from this)
> * Axis and endstop inversion?
> * BLTouch configuration

Hi

I have successfully got the latest Marlin working on a stock TEVO Little Monster will all features working fine.

I had to edit a couple of pins from the MKS SBASE pins file as the thermistors were wrong for the way this was wired...

All required files included in the attached zip. Would be fantastic if this could be added to the official release

[Marlin Files.zip](https://github.com/MarlinFirmware/Configurations/files/7834932/Marlin.Files.zip)

**Comment by thinkyhead** [comment]
Unfortunately the file download link is broken.

**Comment by lemmingDev** [comment]
Are you sure?
I was just able to download the zip file above and extract the 3 files from inside...
In any case, here they are again
[Marlin.Files (1).zip](https://github.com/MarlinFirmware/Configurations/files/7945534/Marlin.Files.1.zip)

**Comment by docman11** [comment]
> > [@lemmingDev](https://github.com/lemmingDev) I attempted to update this for you, but I am not comfortable with the changes I have to make, without having the printer to test it.
> > Do you have a working configuration for a stock Little Monster?
> > The details that I am unsure about:
> > 
> > * Microsteps? 32 or 64? (And the steps/mm derived from this)
> > * Axis and endstop inversion?
> > * BLTouch configuration
> 
> Hi
> 
> I have successfully got the latest Marlin working on a stock TEVO Little Monster will all features working fine.
> 
> I had to edit a couple of pins from the MKS SBASE pins file as the thermistors were wrong for the way this was wired...
> 
> All required files included in the attached zip. Would be fantastic if this could be added to the official release
> 
> [Marlin Files.zip](https://github.com/MarlinFirmware/Configurations/files/7834932/Marlin.Files.zip)

Hi! Thank you for config. Can you specify which marlin version I need to use to compile your config? 2.0.x - got message that need an older version of marlin.......

**Comment by docman11** [comment]
@lemmingDev, I can't find stock TFT28 specified in your configuration.h - what type of screen are you used?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
