### ISSUE TITLE
[FR] CR-10 Max Config

### ISSUE THREAD

**Issue by christianitis** [MarlinFirmware/Configurations#361]
I would like to upgrade my CR-10 Max's firmware, but there is no configuration for it. What should I do? Can someone smarter than me create one, or at least point me in the right direction? Thank you.

**Comment by ellensp** [comment]
I believe there are issues supporting that printers screen in standard Marlin at this time.

InsanityAutomation has a fork of marlin that supports it https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

**Comment by christianitis** [comment]
> I believe there are issues supporting that printers screen in standard Marlin at this time.
> 
> InsanityAutomation has a fork of marlin that supports it https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

Yes, I just tried that. Unfortuneatly it appears that the configuration is out of date: compiling gives me "Please update your configuration." errors. I posted an issue there.

**Comment by ellensp** [comment]
They really want to you use their binaries...

**Comment by christianitis** [comment]
> They really want to you use their binaries...

Who and what are you referring to?

**Comment by ellensp** [comment]
Insanity Automation see all the premade firmwares https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0/Hex%20Files
The key to what all those names means in on the front page https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

**Comment by christianitis** [comment]
> Insanity Automation see all the premade firmwares https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0/Hex%20Files
> The key to what all those names means in on the front page https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

Okay, but what do I do with the hex files?

**Comment by JustinSatu** [comment]
I'm looking for the same configuration files (Configuration.h, Configuration_adv.h, etc...)
I don't want to work with hex files, because I prefer to be able to edit/finetune settings for my CR-10 Max.

**Comment by patnodus** [comment]
Having the same issue

**Comment by patnodus** [comment]
> I'm looking for the same configuration files (Configuration.h, Configuration_adv.h, etc...)
> I don't want to work with hex files, because I prefer to be able to edit/finetune settings for my CR-10 Max.

Did you find what you were looking for? @JustinSatu

**Comment by StudioRATATA** [comment]
+1 
Does anyone have a solution or even the configs to share?

**Comment by patnodus** [comment]
> +1
> Does anyone have a solution or even the configs to share?

I haven't found anything of this yet.  Sorry

**Comment by Tarsonoff** [comment]
Я так же нечего не нашёл! Если найдёте прикрепите пожалуйста.

**Comment by thinkyhead** [comment]
Duplicate of #649
