### ISSUE TITLE
Is there a typo in   CONFIGURATION_H_VERSION 020008  MP_SCARA    ln1175  #define Y_MAX_POS X_BED_SIZE   

### ISSUE THREAD

**Issue by phearl3ss1** [MarlinFirmware/Configurations#362]
Does this configuration for a Scara intentionally define the Y bed max as the X bed Max or is this a typo?  Is this config set up for example to define the Y Min as 0 and 350 max and X as -350 Min and 350 Max (the two arms 
 extended to max radius with zero in the middle Or   0 min for both and 350 Y and 700 Max X?    

Typo in   CONFIGURATION_H_VERSION 020008  MP_SCARA    ln1175  #define Y_MAX_POS X_BED_SIZE    Should be Y_BED_SIZE

**Comment by thisiskeithb** [comment]
You'll have to test it and find out.

SCARA is uncommon hardware and very likely a broken kinematic type in Marlin.

Also, it'd be better to post questions using the following resources before asking questions here:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
