### ISSUE TITLE
TwoTrees Sapphire Plus, double Z enstops with BLTouch

### ISSUE THREAD

**Issue by SpaceEggs24** [MarlinFirmware/Configurations#366]
### Description

Hello, i want to install Marlin using your configuration files but i have problems customizing the configuration files to my needs.
My objective is to use the two Z-axis endstops in combination with the BL-Touch. The BL-Touch should perform a mesh probing sequenze save that and when i want to start printing i want the printer to only use the the Z endstops for homing and the use the before determined mesh to create a perfect first layer. The probe should be connected to the 2. filament runout pins on the board.

I already have this configuration running on my Sapphire Plus but the precompiled firmware is buggy, i dont have any way of configuring it and i dont have the configuration files for reference.

I think this configuration would be a great one for a lot of people with this printer (at least i hope). I'm not to experienced with configuring Marlin so it would be really awesome if you could look into it. Of course i will continue doing my reseach and if i am able to create my own working configuration i will provide it to anyone who's interested.

Thanks!

### Configuration Details

TwoTrees Sapphire Plus V2? Double Z endstops, Double Z TMC2208 drivers, TMC2008 on all axis, BLTouch

* Manufacturer: TwoTrees
* Model: V2?
* Motherboard: MKS Robin Nano V1.2

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
