### ISSUE TITLE
[LINE 1451 CONFIGURATION.h] (Error for #define homing feedrate)

### ISSUE THREAD

**Issue by Spelth** [MarlinFirmware/Configurations#369]
// Homing speeds (mm/min)

LINE 1451 
#define HOMING_FEEDRATE_MM_M { (70*60), (70*60), (4*60) } // This commande define can t be build. For build i replaced it by normal commmande :
#define HOMING_FEEDRATE_XY (70*60)  // And with this normal define for XY define it can be build. 
#define HOMING_FEEDRATE_Z  (4*60)     //And with this normal define for Z define it can be build. 

// Validate that endstops are triggered on homing moves
#define VALIDATE_HOMING_ENDSTOPS

// @section calibrate

/**

**Comment by thisiskeithb** [comment]
Be sure to match configs with the version of Marlin you are compiling for. In this case, you should use `import-2.0.x` or `bugfix-2.0.x` configs with Marlin `bugfix-2.0.x`.

https://github.com/MarlinFirmware/Marlin/pull/20426 was merged into `bugfix-2.0.x` 11 hours ago and configs using XYZ homing feedrates as an array can compile correctly.
