### ISSUE TITLE
[FR] Tagging in Configurations repo

### ISSUE THREAD

**Issue by cociweb** [MarlinFirmware/Configurations#386]
### Description

The commit system is not uniformed for the Marlin and for the Configurations repo. Configurations repo misses the tags (since 2.0.5), meanwhile Marlin repo misses the branches. Is there any plan to uniformize them?

### Configuration Details

N/A

#### Additional Information

N/A

Thank You!

**Comment by thinkyhead** [comment]
"Tags" are a nice convenience, but they mainly apply to a unary development tree where you pile up some commits and add a tag to it. Apart from the endless rolling `import-2.0.x` branch, the branches in this repository are all generated by script. So each Marlin version has a programmatically-generated configuration branch just for it. This also allows for making small adjustments to these branches at any time, without being concerned for their impact on the other branches or how they fit into past 'history'.
