### ISSUE TITLE
Ender3-Pro V1 config doesn't compiles 

### ISSUE THREAD

**Issue by Manolo8888** [MarlinFirmware/Configurations#389]
### Description
When I compile Ender3-Pro V1 config, doesn't fit on a V1.1.4, or sanguino device.  

### Configuration Details
* Manufacturer: Creality
* Model: Ender3-Pro
* Motherboard: V1.1.4

#### Additional Information
In Arduino enviroment dosn't compile, it fires an error about no enought space.

**Comment by ellensp** [comment]
Use vscode + platformio, it produces smaller code.

RAM:   [===       ]  27.9% (used 4563 bytes from 16384 bytes)
Flash: [==========]  97.9% (used 124252 bytes from 126976 bytes)

**Comment by Manolo8888** [comment]
Yes, it works, thank you very much
