### ISSUE TITLE
I send X-Axis move = Y Axis moves l I send Y-Axis move = Y Axis moves l How to solve?

### ISSUE THREAD

**Issue by TomF100** [MarlinFirmware/Configurations#432]
Hello,

i m using the most recent marlin firmware and got the problem that now the Y-Axis is moving in both cases of X-Axis and Y-Axis. I m have some experience with the marlin firmware but do not know we to look for a solution.

About any advice I would be very happy.

Regards

Tom

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
