### ISSUE TITLE
[BUG] In complete documentation on Tronxy X5SA howto

### ISSUE THREAD

**Issue by thawkins** [MarlinFirmware/Configurations#436]
### Bug Description

In the file config/examples/Tronxy/X5SA/HOWTO-INSTALL.md

Issue1. The platformio config is not given, what processor?

Issue2. 
page says

"After you compile Marlin with the above instructions, it will generate a file: YOUR-MARLIN-DIR/.pio/build/chitu_f103/update.cbd" 

but there are NO compile instructions on the page

**Comment by ellensp** [comment]
Listed in platfomio.ini
```
#
# Chitu boards like Tronxy X5s (STM32F103ZET6)
#
[env:chitu_f103]

```
also this is in the build path you quoted. chitu_f103

Further it is in the manual how to find out the build environment.

https://marlinfw.org/docs/basics/install_platformio_vscode.html

```
Identifying your board’s environment
The PlatformIO environment needed for a motherboard is in the comments for the board in the pins.h file. In Marlin 2.0 it’s located in a subdirectory Marlin/src/pins/pins.h.

Example:

The Configuration.h file says #define MOTHERBOARD BOARD_RAMPS_14_EFB

Search the pins.h file for RAMPS_14_EFB until you come to the following:

  #elif MB(RAMPS_14_EEB)
     #include "pins_RAMPS.h"     // ATmega1280, ATmega2560  env:megaatmega1280 env:megaatmega2560
The first part of the comment lists the CPU(s) used in the board.

The env:xxxx section(s) are the PlatformIO environment(s) that are used for this board.
```

Also if you use marlin autobuild it give you a gui with the correct options.

Lastly if your running bugfix and don't set the correct build environment, it will tell you the correct build environments you can choose.

`Error: Build environment 'mega2560' is incompatible with BOARD_CHITU3D_V5. Use one of these: chitu_f103,chitu_v5_gpio_init
`
