### ISSUE TITLE
Geeetech Delta G2SPro - 3D Touch configuration

### ISSUE THREAD

**Issue by edicsonm** [MarlinFirmware/Configurations#439]
Hi, I am having some issues with version 2.0.7.2 when trying to configure 3D Touch.  If I enable  //#define BLTOUCH and disable // #define Z_PROBE_ALLEN_KEY in Configuration.h my Z max endstop is not used any more. If I try to home the printer the X and Y endstops are reached but not the Z one. I am using the configurations files from https://github.com/MarlinFirmware/Configurations/tree/2.0.7.2/config/examples/delta/Geeetech/G2SPro. Has anyone done that configuration before?. My delta has a Geeetech GT2560 Rev. A+ (with auto level probe) board. The 3DTouch is working. It is triggered and retracted accordingly.

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
