### ISSUE TITLE
SKR mini e3 v1.2 Z axis noise on Ender 3 Pro

### ISSUE THREAD

**Issue by bgobrecht** [MarlinFirmware/Configurations#44]
Ender 3 Pro: Skr mini e3 v1.2 + TFT35 v3 + OctoPrint 

I have been trying to figure out a way to get the Z axis to stop making noise since 2.0.4.4 I have not been able to. Anything before this release they all have been silent. wondering if there is a way to get all to be silent again. 

thanks

**Comment by jerryfudd** [comment]
comment out hybrid threshold
