### ISSUE TITLE
tronxy chitu_v6 no longer option[BUG] (short description)

### ISSUE THREAD

**Issue by cetsdarkside** [MarlinFirmware/Configurations#443]
tronxy X5SA

 `Configuration.h` 
no options on v6 board?
is there much needed to change in the settings?

line 130-135 choose the name from boards that match your setup.

i tried to copy text over but doesnt show in comment?

 <!--
 // Choose the name from boards.h that matches your setup
 #ifndef MOTHERBOARD
   #define MOTHERBOARD BOARD_CHITU3D_V5
 #endif

 // Name displayed in the LCD "Ready" message and Info menu
 #define CUSTOM_MACHINE_NAME "Tronxy X5SA"
 Please follow the instructions below. Failure to do so may result in your issue being closed.

**Comment by ellensp** [comment]
BOARD_CHITU3D_V6 is in marlin.....
