### ISSUE TITLE
Anet A8 Full Graphics LCD Marlin 2.0.7.2 Sync Issue

### ISSUE THREAD

**Issue by 400killer** [MarlinFirmware/Configurations#450]
### Bug Description
Using the new Marlin 2.0.7.2 with the Anet A8 and the Anet Full graphics display, did not work. It would power on, and everything worked, except the screen. The display had a lot of image tearing, showing it had syncing issues and was fixed by adding the three lines noted below.

### Configuration Files
I had to add the three lines under the "ANET_FULL_GRAPHICS_LCD" entry in the configuration.h file to fixed the sync issues. A forum suggested using the the C10 display, but the variable names are a little different. It has "BOARD_" as a prefix, and it presents errors with the Anet config. 

Please add these variable to the "Conditionals_LCD.h" files after line 106 for other Anet users updating with the full graphics display.

#define ANET_FULL_GRAPHICS_LCD
#define ST7920_DELAY_1 DELAY_NS(150)
#define ST7920_DELAY_2 DELAY_NS(150)
#define ST7920_DELAY_3 DELAY_NS(150)

### Steps to Reproduce
Installed the stock ANET config files with the ANET_FULL_GRAPHICS_LCD uncommented since I had that display connected.

**Expected behavior:**
The Display would work as expected and be legible.

**Actual behavior:**
The image was very torn due to a syncing issue. The rotary encoder, speaker, and reset button worked as expected. Added three lines noted above fixed the tearing issue.

* Manufacturer: ANET 
* Model:A8
* Motherboard: V1

[New folder.zip](https://github.com/MarlinFirmware/Configurations/files/6218265/New.folder.zip)

**Comment by Vertabreak** [comment]
suggest submitting a pull request with the noted change for review.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by thinkyhead** [comment]
Often these delays are more closely associated with the board than with the display. See MarlinFirmware/Marlin#22641 for changes that aim to wrangle the specified delays.
