### ISSUE TITLE
[FR] (configuration request Geeetech A10T)

### ISSUE THREAD

**Issue by EtMariellche** [MarlinFirmware/Configurations#453]
### Configuration Details

* Manufacturer: Geeetech
* Model: A10T
* Motherboard:Atmega GT2560 V4

#### Additional Information

* Provide links to the requested printer/configuration. 
* https://www.geeetech.com/geeetech-a10t-3-in-1-out-mixcolor-auto-leveling-3d-printer-p-1107.html
* https://www.geeetech.com/gt2560-v40-control-board-for-a10t-printer-p-1164.html
* https://www.geeetech.com/stepper-driver-a4988-with-heatsink-and-sticker-p-1007.html
* https://www.geeetech.com/titan-extruder-kit-for-a10m-a10t-a20m-a20t-a30m-a30t-p-1131.html
* https://www.geeetech.com/geeetech-a10-a10m-a10t-heatbed-kit-p-1104.html
* https://www.geeetech.com/download.html?download_id=49, the Firmware is .hex only.

**Comment by Vertabreak** [comment]
this already exists there is no difference between a gt2560 revb/v3.x/v4.x.
i even added shell pins that only change the name of the board.
the models with v4.1 board have a different screen and i added examples for this also.

https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Geeetech
https://github.com/MarlinFirmware/Marlin/commits/bugfix-2.0.x?author=vertabreak
https://github.com/MarlinFirmware/Configurations/commits?author=vertabreak

**Comment by EtMariellche** [comment]
I will try it. Thank you so far.
