### ISSUE TITLE
[FR] (configuration request Anycubic Mega Zero 2.0)

### ISSUE THREAD

**Issue by EtMariellche** [MarlinFirmware/Configurations#454]
### Configuration Details

* Manufacturer: Anycubic
* Model: Mega Zero 2.0
* Motherboard: Mega Zero 0.0.3 (Melzi-Board mit) ATMega 1284P U-TW

#### Additional Information

* Provide links to the requested printer/configuration.
* https://www.anycubic.com/collections/anycubic-mega-3d-printers/products/mega-zero-2-0-fdm-3d-printer
* https://github.com/ANYCUBIC-3D/MEGA_ZERO
* https://drucktipps3d.de/anycubic-mega-zero-2-0/

**Comment by ellensp** [comment]
Please carefully test this PR https://github.com/MarlinFirmware/Configurations/pull/458
I do not have this machine to try it on.

**Comment by ellensp** [comment]
Can you please try these Configs
