### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by napter** [MarlinFirmware/Configurations#459]
### Bug Description

The Ender 5 Plus config has both LIN_ADVANCE and S_CURVE_ACCELERATION on. So the configuration sample for that printer won't compile and instead throws this error "Marlin\src\HAL\AVR\../../inc/SanityCheck.h:1022:6: error: #error "LIN_ADVANCE and S_CURVE_ACCELERATION may not play well together! Enable EXPERIMENTAL_SCURVE to continue."

### Configuration Files

I have made no modifications, just use the config files from Creality/Ender 5 plus directory

### Steps to Reproduce

Try building using the config files mentioned above and it throws an error. 

The default configuration should be edited to either disable S_CURVE_ACCELERATION or enable EXPERIMENTAL_SCURVE. Which is the preferred option?

**Comment by thinkyhead** [comment]
A search for regex `^ *#define (LIN_ADVANCE|S_CURVE_ACCELERATION)\b` in release-2.0.7.2 and the import-2.0.x branch turns up no configurations with `LIN_ADVANCE` and `S_CURVE_ACCELERATION` enabled, so this can be closed.
