### ISSUE TITLE
[BUG] CrealityV422/Configuration_adv.h Babystep

### ISSUE THREAD

**Issue by Poporacer** [MarlinFirmware/Configurations#466]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

In the Configuration_adv.h file for the Creality Ender 3 Pro and the Ender 3 V2 the code has an incorrect value for 

#define BABYSTEP_MULTIPLICATOR_Z  40

This creates a very large step, the Default value on the Ender 3 and most of the other printers is:

#define BABYSTEP_MULTIPLICATOR_Z  1

Changing to this value gives you the small steps you need to properly adjust your printer.

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
Since you've provided a fix, it'd be faster if you submitted a [Pull Request](https://marlinfw.org/docs/development/getting_started_pull_requests.html) so it can be reviewed.
