### ISSUE TITLE
[BUG] 12864 white screen - with solution

### ISSUE THREAD

**Issue by dgpower** [MarlinFirmware/Configurations#470]
12864脱机模块白屏问题及解决方案    12864 offline module white screen problem and its solution
------------------------------------------------
我尝试用最新的marlin固件版本，包括最新bugfix和marlin2.0.7.2，发现只要我液晶显示器配置了中文菜单（zh_cn），刷新固件后液晶显示器上就是一片空白，没有任何字符。
![不正常](https://user-images.githubusercontent.com/23353724/115024008-16febe80-9ef2-11eb-9576-b5bf2a875268.jpg)

经过无数次的测试，我发现，只要不打开EEPROM功能，就可以正常显示
![EEPROM配置](https://user-images.githubusercontent.com/23353724/115024188-53cab580-9ef2-11eb-88e5-029c169e3635.png)

![正常](https://user-images.githubusercontent.com/23353724/115024140-4281a900-9ef2-11eb-800b-5a263c189d64.jpg)

后面我做了测试，同样的固件设置，打开EEPROM，但是用英文（en）字符，12864的显示就是正常的。

我怀疑是因为用了中文字符，又打开了许多的功能菜单，比如，自动调平、四角调平等等，导致LCD12864的运行内存满了。

我水平有限，不知道该如何检查12864脱机打印模块的内存使用情况。

只是在这里发布一下，希望对其他人有帮助。

如果可能的话，建议开发者测试一下，看看是不是我说的内存问题。

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by dgpower** [comment]
[Marlin.zip](https://github.com/MarlinFirmware/Configurations/files/6325083/Marlin.zip)

**Comment by thinkyhead** [comment]
> the operating memory of the LCD12864 is full

That is unlikely. It stores nothing. Marlin controls it 100%.

But as you discovered, you can turn off features to get some SRAM back. It doesn't have to be EEPROM.

Anyway, version 2.0.8 will be released soon. It has many improvements.
