### ISSUE TITLE
[BUG] problem with U8GLIB

### ISSUE THREAD

**Issue by riton13** [MarlinFirmware/Configurations#471]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by ellensp** [comment]
No information provided. no error messages, screenshots, configuration files,  nothing.
