### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by EtMariellche** [MarlinFirmware/Configurations#477]
### Bug Description

Processing mega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
Error: Build environment 'mega2560' is incompatible with BOARD_MELZI_CREALITY. Use one of these: melzi_optiboot_optimized, melzi_optiboot, melzi_optimized, melzi
=============================================================================================== [FAILED] Took 0.64 seconds =============================================================================================== 

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:00.638
========================================================================================== 1 failed, 0 succeeded in 00:00:00.638 ==========================================================================================The terminal process "C:\Users\myusername\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
[MarlinAnyCubicMegaZero2_0.zip](https://github.com/MarlinFirmware/Configurations/files/6410287/MarlinAnyCubicMegaZero2_0.zip)

### Configuration Files

Attached .zip File with unmodified configuration Files.
### Steps to Reproduce

1. [First Step] Installed VSCode from https://code.visualstudio.com/
2. [Second Step] Downloaded Marlin 2.0.8 from https://marlinfw.org/meta/download/ and Configurations from https://github.com/MarlinFirmware/Configurations/tree/release-2.0.8
3. [and so on...] Started VSCode and opend Marlin-2.0.x Folder
4. Clicked on configuration.h
5. Connected Printer Com6
6. Clicked on the PlatformIO Build Icon
7. recieved Error Message shown in the Bug Description

**Expected behavior:**

I allready successfully uploaded a previous Marlin 2.0.x Version to the Anycubic Mega Zero 2.0 Printer. 
I got this Firmware from TH3D called Unifyed Firmware 2. 
I expected the latest Marlin Firmware with the configuration Files for the Anycubic Mega Zero 2.0 to Build and Upload easiely.

**Actual behavior:**

It appears to be the wrong Board, if i understand the returned Error correctly.

#### Additional Information
I followed the Steps from https://support.th3dstudio.com/hc/downloads/unified-2-firmware/anycubic/anycubic-mega-zero-v1-v2-firmware-melzi-board/
I tryd the Release, Import and the bugfix Version.
I allready uninstalled and cleaned the System from VSCode with bulk crap uninstaller.

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
This is not a bug:

> Error: Build environment 'mega2560' is incompatible with BOARD_MELZI_CREALITY. Use one of these: melzi_optiboot_optimized, melzi_optiboot, melzi_optimized, melzi

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
