### ISSUE TITLE
Flyingbear P905H dual extruder,   MKS ROBIN NANO V3.0 32bits,   TS35 v2.0,  5un TMC2209 V1.0

### ISSUE THREAD

**Issue by cabinho** [MarlinFirmware/Configurations#482]
* Manufacturer:
* Model:               Flyingbear P905H  dual extruder
* Motherboard:    MKS ROBIN NANO V3.0   32bits,     TS 35 v2.0,     5unidades TMC2209 v1.0

model original site -   https://pt.aliexpress.com/item/32847075621.html

I was unable to configure the autoleveling bed and X Y Z movement

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
