### ISSUE TITLE
[BUG] M92 negative value destroy config

### ISSUE THREAD

**Issue by Arut42** [MarlinFirmware/Configurations#493]
### Steps to Reproduce

write "M92 E-137.5" to the printer 
write "M500" to the printer to write to flash and finaly it wount work until you reset to default

**Expected behavior:**

printer should invert the axis

**Actual behavior:**

no more movement possible until reset

**Comment by ellensp** [comment]
Not related to example marlin configs, which is what this github is all about.

Please create issue  in  https://github.com/MarlinFirmware/Marlin/issues/new/choose

**Comment by thinkyhead** [comment]
We advise that you don't do that.
