### ISSUE TITLE
Configuring laser on creality 4.2.7 board

### ISSUE THREAD

**Issue by sanscorp1** [MarlinFirmware/Configurations#497]
Not really an issue but I can only find documentation on the laser/spindle config on the 8 bit boards.

I have build a custom frame with an Creality 4.2.2. board and don't have Z and E axis, nor temp. sensors.

I have little experience with C++ but I would like to make a clean code just for X Y axis and PWM "fan" (laser) control.

Can I comment out or even delete all code regarding temp and extruder in the configuration files or are there references/dependencies that would kill the FW?

How would I prevent errors on homing Z or temp warnings otherwise?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
