### ISSUE TITLE
[BUG] REPRAP_DISCOUNT_SMART_CONTROLLER SD_DETECT_STATE for Anycubic Kossel Linear Plus has wrong default state

### ISSUE THREAD

**Issue by tig33r** [MarlinFirmware/Configurations#501]
My printer: stock anycubic kossel linear plus but skr 1.3 instead of trigorilla.

\config\examples\delta\Anycubic\Kossel Linear Plus\Configuration_adv.h

SD_DETECT_STATE pin should have low state

After insertion sd card on display we have "Media removed".
After ejection sd card on display we have "SD init fail".

current config:

  // The standard SD detect circuit reads LOW when media is inserted and HIGH when empty.
  // Enable this option and set to HIGH if your SD cards are incorrectly detected.
  #define SD_DETECT_STATE HIGH

should be changed to:

  // The standard SD detect circuit reads LOW when media is inserted and HIGH when empty.
  // Enable this option and set to HIGH if your SD cards are incorrectly detected.
  //#define SD_DETECT_STATE HIGH

This is most probably connected with https://github.com/MarlinFirmware/Marlin/pull/21885/

**Comment by ellensp** [comment]
PR created, this will be updated soon.
