### ISSUE TITLE
Ender 5 plus Z endstop doesn't work

### ISSUE THREAD

**Issue by bartoszwas** [MarlinFirmware/Configurations#508]
Is there any info to which atmega's pin Z end stop is connected?

I have always open z end stop using Ender 5 Plus configuration on Creality 2.2.1 motherboard.

**Comment by ellensp** [comment]
Enable PINS_DEBUGGING in Configuration_adv.h 
Then send a M43 at the printer, it will list what is on all the pins.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
