### ISSUE TITLE
upload problem - For Creality Silentboard V4.2.7 with STM32F103-RET6

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Configurations#511]
Hi i can´t upload config to board. 

Any idea how to solve it?

**Comment by ellensp** [comment]
You don't upload config's to the board.

You compile the firmware using the example configs then copy the generated firmware.bin to the sdcard and insert that into the printer.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
