### ISSUE TITLE
ender 3 max w/BL touch request

### ISSUE THREAD

**Issue by endl** [MarlinFirmware/Configurations#522]
would really like a working example config for this set up and/or one with a SKR mini e3 v2 as the main board

**Comment by thinkyhead** [comment]
Someone with the hardware will have to tackle the problem. If you figure it out please submit your results.

**Comment by LTSpenny** [comment]
I can make one. I have one configured for the SKR E3 Turbo that i can make changes to suit yours. How do i add a config example to the repository?

**Comment by endl** [comment]
No idea I'm not even sure half my settings are correct or working properly

**Comment by LTSpenny** [comment]
@endl well i can make one and just link it for you. What board do you want it for. Skr mini e3?

**Comment by endl** [comment]
Yea skr mini e3 v2

**Comment by LTSpenny** [comment]
https://drive.google.com/drive/folders/1blPp7cNIaFi7SdDJ0D_c9sSqE35h3H9x?usp=sharing

try this configuration, its mostly what I'm running on my max. Hope that gives you a good starting point, make sure you compile in the right environment. Also this was a config file from the last bug build a few days ago, did not check if there's been an update on that. Cheers.

can upload the full source i used if needed.

**Comment by LTSpenny** [comment]
Please close ticket if this solved your problems.
