### ISSUE TITLE
i dont know how to do this

### ISSUE THREAD

**Issue by ivancamacho8** [MarlinFirmware/Configurations#534]
I had modified code in probe.cpp, changed 
`//    #elif ENABLED(BLTOUCH_HS_MODE)`
to
`    #elif 1`
The result is G28, G29, M401 and M402 can control the BLTouch. "M43 S" also works.
For M401/402 I am sure that it didn't work before this modification. What I remember, the behaviour of G28 was unexpected, first it homed X and Y as ussual, then pull up Z and stopped. So I started to troubleshoot the bl-touch. This effect could be triggered by this sw fault or some other issue with my bl-touch.

_Originally posted by @mel4321 in https://github.com/MarlinFirmware/Marlin/issues/17440#issuecomment-611550847_

I don't understand how to modify code in probe.cpp anyone can explain it to me? I'm knew with 3d printing and I think my printer has this problem

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
