### ISSUE TITLE
[BUG] (AU20 problem with bl touch calibration)

### ISSUE THREAD

**Issue by Dezmonius** [MarlinFirmware/Configurations#537]
Hello,  I have issues with bl touch calibration on AlfawiseU20 based on MKS Gen L V2.0 When bl touch starts calibration it scans a half of my printer bed and nozzle to probe offset doesnt work, only probe margin 60 can help bl touch to start calibration on correct corner of printer. Someone has this problem earlier? (Sorry for my bed english)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
