### ISSUE TITLE
[FR] Support for Creality CR-200B

### ISSUE THREAD

**Issue by mcecchi** [MarlinFirmware/Configurations#556]
### Description

Configuration for Creality CR-200B fully enclosed 3d printer

### Configuration Details

* Manufacturer: Creality
* Model: CR-200B
* Motherboard: Creality 3D CR-200B Motherboard v4.2.5

**Comment by mcecchi** [comment]
Good starting point https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

**Comment by thinkyhead** [comment]
Duplicate of #649
