### ISSUE TITLE
Mesh Bed Leveling an Anet A8 with new firmware installed

### ISSUE THREAD

**Issue by somebody-said** [MarlinFirmware/Configurations#56]
4/1/2020 6:58:36 PM

Hello,

Information sought

Instead of repeating what may have already been discussed and closed, we are seeking guidance of how to locate in GitHub a description of how to correctly perform the necessary steps to achieve Mesh Bed Leveling on an Anet A8 3D Printer.  After installing the listed firmware in the attached image on an Anet V1.7 motherboard and without using any potentiometer knob, probe or sensor thus relying on the original buttons for manual controls of the printer menus, we are not able to correctly level the bed.
![5-Firmware and all zip files used thus far](https://user-images.githubusercontent.com/62589617/78165145-2e841a00-744b-11ea-8865-0b7eeb021955.png)

The newly installed firmware accurately provided the following:
// The size of the print bed
#define X_BED_SIZE 220
#define Y_BED_SIZE 220

// Travel limits (mm) after homing, corresponding to endstop positions.
#define X_MIN_POS -33
#define Y_MIN_POS -10
#define Z_MIN_POS 0
#define X_MAX_POS X_BED_SIZE
#define Y_MAX_POS Y_BED_SIZE
#define Z_MAX_POS 240

Problem
Our problem occurs when mesh leveling moves the extruder completely off the bed in the X axis and Y axis after initially beginning the first mesh point on the lower left corner of the bed.

**Comment by thinkyhead** [comment]
If you think this is a bug please report it to the Marlin project and fill out the complete template. But before you assume it is a bug you should seek support from one of these community forums:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
