### ISSUE TITLE
NeoPixel

### ISSUE THREAD

**Issue by LunerStorm** [MarlinFirmware/Configurations#560]
* Manufacturer: Creality
* Model: Ender 5
* Motherboard: SKR mini e3 v2
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/7080032/Configuration.zip)

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by LunerStorm** [comment]
Hi Keith  Pretty sure this is a bug as I can get it working in 2.0.6. However 2.0.9.1 compiles but does not work.DonSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Keith Bennett ***@***.***> Date: 8/30/21  4:39 PM  (GMT-07:00) To: MarlinFirmware/Configurations ***@***.***> Cc: LunerStorm ***@***.***>, Author ***@***.***> Subject: Re: [MarlinFirmware/Configurations] NeoPixel (#560) 
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on this page.) For best results getting help with configuration and troubleshooting, please use the following resources:

Marlin Documentation hosted on MarlinFW.org
Marlin Forum hosted on RepRap.org
Marlin Firmware Facebook Group
Marlin Firmware for 3D Printers Facebook Group
Marlin Configuration on YouTube
Marlin Firmware Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.

**Comment by thisiskeithb** [comment]
> Hi Keith  Pretty sure this is a bug as I can get it working in 2.0.6. However 2.0.9.1 compiles but does not work.DonSent from my Verizon, Samsung Galaxy smartphone

Please file a proper bug report in the correct repo: [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBUG%5D+%28bug+summary%29).
