### ISSUE TITLE
TELA DA SAPPHIRE PLUS INVERTIDA (CABEÇA PARA BAIXO)

### ISSUE THREAD

**Issue by ngoliveira** [MarlinFirmware/Configurations#564]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.
![20210906_152103](https://user-images.githubusercontent.com/90214137/132252350-dc9f4caa-9ee6-4cc5-af9a-c75ade2331e3.jpg)
![20210906_152103](https://user-images.githubusercontent.com/90214137/132252378-338e5583-27a0-4c79-b31f-e665d03cf313.jpg)

**Comment by ngoliveira** [comment]
> 

> [``](url)

**Comment by willngton** [comment]
You haven't upload your config files, please check if the fallowing directive are enable:

#define TFT_ROTATION TFT_ROTATE_180

If now, just add and it should be fine.

**Comment by thisiskeithb** [comment]
Do you have a V1 or V2 [Two Trees Sapphire Plus](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Two%20Trees/Sapphire%20Plus)?

We don't have configs for the V1.

`TFT_ROTATION` is disabled for for the V2 config (so not rotated), but as @willngton noted, enable `#define TFT_ROTATION` and set it to `TFT_ROTATE_180` since your TFT appears to be 180 degrees out.

We'll need someone with a V1 and V2 to confirm which settings are correct and update settings/readmes accordingly.

**Comment by ngoliveira** [comment]
I have a Sapphire V2 with two Z motors.
I'll try to make the change and see if it's resolved...
Thank you for your help!

**Comment by ngoliveira** [comment]
> Você tem um V1 ou V2 [Two Trees Sapphire Plus](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Two%20Trees/Sapphire%20Plus) ?
> 
> Não temos configurações para o V1.
> 
> `TFT_ROTATION`está desabilitado para uma configuração V2 (portanto, não girado), mas como @willngton observou, habilite `#define TFT_ROTATION`e desejados-o como `TFT_ROTATE_180`já que seu TFT parece estar 180 graus fora.
> 
> Precisaremos de alguém com V1 e V2 para confirmar quais configurações estão corretas e atualizar conforme configurações / leia-me de acordo.

Vou tentar fazer a alteração e aviso se foi resolvido...

Obrigado pela ajuda!

**Comment by ngoliveira** [comment]
I made the modification and it didn't work... The screen remains inverted.
Is there another command line to modify?
I also tested the X,Y and Z movements, and the "Z" axis movement is also inverted.
My Sapphire has five TCM2208 drivers.

![STEPERS](https://user-images.githubusercontent.com/90214137/132445620-0d9df20c-9059-4782-af14-050627a34293.JPG)

**Comment by thinkyhead** [comment]
> The screen remains inverted.

You can also try all these various options…
```cpp
/**
 * TFT Rotation. Set to one of the following values:
 *
 *   TFT_ROTATE_90,  TFT_ROTATE_90_MIRROR_X,  TFT_ROTATE_90_MIRROR_Y,
 *   TFT_ROTATE_180, TFT_ROTATE_180_MIRROR_X, TFT_ROTATE_180_MIRROR_Y,
 *   TFT_ROTATE_270, TFT_ROTATE_270_MIRROR_X, TFT_ROTATE_270_MIRROR_Y,
 *   TFT_MIRROR_X, TFT_MIRROR_Y, TFT_NO_ROTATION
 */
#define TFT_ROTATION TFT_NO_ROTATION
```
The final result ends up being made with this combination of conditionals…
```cpp
#define TFT_DEFAULT_ORIENTATION (TFT_EXCHANGE_XY | TFT_INVERT_X | TFT_INVERT_Y)
#define TFT_ORIENTATION ((TFT_DEFAULT_ORIENTATION) ^ (TFT_ROTATION))
#define ILI9488_ORIENTATION IF_0((TFT_ORIENTATION) & TFT_EXCHANGE_XY, ILI9488_MADCTL_MV) | \
                            IF_0((TFT_ORIENTATION) & TFT_INVERT_X,    ILI9488_MADCTL_MX) | \
                            IF_0((TFT_ORIENTATION) & TFT_INVERT_Y,    ILI9488_MADCTL_MY)
```

> I also tested the X,Y and Z movements, and the "Z" axis movement is also inverted.

That is an easy fix and well-documented. Take your pick:
```cpp
#define INVERT_Z_DIR false
#define INVERT_Z_DIR true
```

**Comment by ngoliveira** [comment]
Ola!
Consegui resolver o problema da tela invertida.

Agora consegui testar o Marlin, porém não consigo fazer funcionar o HOMiNG do eixo Z... Sempre que acionado para fazer o Homing Z, faz um barulho como se os motores estiverem pulando passo... Dá a impressão de que um dos motores está com a rotação invertida... @thinkyhead; @cabeça pensante; @willngton

**Comment by thinkyhead** [comment]
For best results getting help from smart people, migrate over to Discord… Join link: https://discord.gg/n5NJ59y
