### ISSUE TITLE
MKS robin e3d v1.1+TMC2130 SPI Fail

### ISSUE THREAD

**Issue by Warober** [MarlinFirmware/Configurations#565]
Hi I have a problem with MKS robin e3d v1.1.
The problem is that if I load Marlin (2.0.9.1) with the TMC2130, the MKS MINI12864 V3 LCD screen freezes at startup, the Marlin logo appears and crashes. I have tried compiling with TMC2130_STANDALONE and it boots perfectly. I have also tried another screen and the error is the same.
The bug is caused by activating the SPI function of the drivers.
Thanks greetings

**Comment by thisiskeithb** [comment]
Please open a [proper bug report](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBUG%5D+%28bug+summary%29) in the main Marlin repo.
