### ISSUE TITLE
FlyingBear/P902

### ISSUE THREAD

**Issue by DoctorDeatch** [MarlinFirmware/Configurations#568]
Hi friends, I am sharing the working configuration for the FlyingBear P902 printer 
[https://yadi.sk/d/nmhB9kNxia3SvA](url)
[https://yadi.sk/d/x-tyc8Z_8JuwWw](url)

**Comment by ellensp** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/7164976/Configuration.zip)
Since links are broken, I have attached them locally.

**Comment by DoctorDeatch** [comment]
thanks a lot

**Comment by thisiskeithb** [comment]
Added in https://github.com/MarlinFirmware/Configurations/pull/569
