### ISSUE TITLE
[BUG] (delta generic for BTT skr pro v1.2)

### ISSUE THREAD

**Issue by Enzo-Enz** [MarlinFirmware/Configurations#573]
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
I'm not sure what kind of bug you're reporting since you didn't bother to fill anything out, but you can adapt the generic delta config to any printer: https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/delta/generic

**Comment by Enzo-Enz** [comment]
hello guys

I faced with an error while compiling delta generic configuration for BTT skr pro v1.2:

error says:



![Screenshot (2)](https://user-images.githubusercontent.com/75531691/134312881-320be872-eded-4903-ae08-3d524c35f5bf.png)
![Screenshot (3)](https://user-images.githubusercontent.com/75531691/134312906-662bf6db-30ed-46a1-a3ec-a74b245584ae.png)
![Screenshot (4)](https://user-images.githubusercontent.com/75531691/134312925-472c1e77-e08f-4e53-8ced-e6000f3ea6c5.png)

is there any way to solve that?

**Comment by thisiskeithb** [comment]
The error message is telling you to set a `PS_ON_PIN` if you have `PSU_CONTROL` enabled.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Enzo-Enz** [comment]
thanks for replaying

sorry may I ask you to explain more about it because it is my first time using skr board and and I don't know which part have to be changed for ps on pin

**Comment by ellensp** [comment]
The BTT skr pro v1.2 does not have a dedicated pin for PSU_CONTROL.
So if your using that feature you need to add a #define PS_ON_PIN {pin your using as the psu control pin} to your Configuration.h 
Or disable  #define PSU_CONTROL in Configuration.h to turn off the feature by adding // in the front of that line.

**Comment by Enzo-Enz** [comment]
thank you so much bro 
the error fixed
