### ISSUE TITLE
Unable to set Z-axis on Creality CR-20 Pro on 2.0.9.1

### ISSUE THREAD

**Issue by joericki** [MarlinFirmware/Configurations#578]
### Bug Description

I compiled the latest buxfix 2.0.x version for Crealtiy CR-20 Pro and installed it on my printer without any issues. However, when I try to set the Z-axis in the same manner as I did in my previous verison (also attached) I could move it into the negative but the print head didn't move at all. Here the steps I took:
_```
Setting the Probe Z Offset
1. Heat the printer up to 200 celcius on the nozzle, 60 on the bed
2. Auto home the printer
3. Move the printer's Z axis to zero. Make sure you have your paper
underneath the nozzle before doing this
4. Go to the configuration > probe z offset menu. Move the Z offset into the
negative range until it start to grip the paper
5. Save the settings by clicking configuration > store settings.
```_


### Configuration Files

Below the new configuration files:
[CR20Pro_2.0.9.1.zip](https://github.com/MarlinFirmware/Configurations/files/7231408/CR20Pro_2.0.9.1.zip)
Made no modifications

Here the old configuration files which worked without the issue mention above and which I've reinstalled now:
[CR-20Pro-3DPC-Update.zip](https://github.com/MarlinFirmware/Configurations/files/7231413/CR-20Pro-3DPC-Update.zip)

### Steps to Reproduce

I've compiled the normal 2.0.9.1 version as well as the bugfix version serveral times always with the same result

**Expected behavior:**

I expect that the Z-axis can be properly adjusted to the bed level.

**Actual behavior:**
As described above the Z-axis cannot be moved to the appropriate level (printing in the air!)

#### Additional Information
none

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
