### ISSUE TITLE
[FR] Anycubic I3 Mega (Trigorilla RAMPS 1.4)

### ISSUE THREAD

**Issue by Digifan** [MarlinFirmware/Configurations#579]
### Description

Please help with configuration file for Anycubic I3 Mega (Trigorilla RAMPS 1.4 not v.1.1) I try to use configuration files from bugfix brunch, but always got the error as below:

Linking .pio\build\mega2560\firmware.elf
C:...\Local\Temp\cczv8kV9.ltrans1.ltrans.o: In function `Temperature::wait_for_bed(bool, bool)':
<artificial>:(.text+0x682a): undefined reference to `MarlinUI::lcd_clicked'
<artificial>:(.text+0x682e): undefined reference to `MarlinUI::lcd_clicked'
C:\Users\stell\AppData\Local\Temp\cczv8kV9.ltrans1.ltrans.o: In function `Temperature::wait_for_hotend(unsigned char, bool, bool)':
<artificial>:(.text+0x6b44): undefined reference to `MarlinUI::lcd_clicked'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mega2560\firmware.elf] Error 1
==================================== [FAILED] Took 30.77 seconds ====================================
>

### Configuration Details

<AI3M in stock>

* Manufacturer: Anycubic
* Model: I3 Mega
* Motherboard: Trigorilla Ramps 1.4

#### Additional Information

* Provide links to the requested printer/configuration
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/7231613/Configuration.zip)
.

**Comment by ellensp** [comment]
https://github.com/MarlinFirmware/Marlin/issues/22836 
Use bugfix code and provided updated configuration files
