### ISSUE TITLE
[BUG] 2.0.9.2. breaks Sensorless Homing in combination with DELTA_AUTO_CALIBRATION

### ISSUE THREAD

**Issue by Vabe7** [MarlinFirmware/Configurations#584]
### Bug Description

Using the Standard Kossel Mini Configuration the compilation fails if SENSORLESS_HOMING and DELTA_AUTO_CALIBRATION are both enabled. It fails with `Marlin\src\gcode\calibrate\G33.cpp:76:28: error: 'probe' was not declared in this scope`.

### Configuration Files

[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/7310177/Configuration.zip)

### Steps to Reproduce

Download 2.0.9.2 or latest bugfix, download Kossel Mini configuration, set driver to TMC2209, enable SENSORLESS_HOMING, DELTA_AUTO_CALIBRATION, PROBE_MANUALLY and disable Z_PROBE_ALLEN_KEY and Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN.

**Expected behavior:**
Should compile like in 2.0.9.1.

**Actual behavior:**
Fails with before mentioned error message.

**Comment by ellensp** [comment]
In Marlin/src/gcode/calibrate/G33.cpp is

```CPP
void ac_home() {
  endstops.enable(true);
  TERN_(SENSORLESS_HOMING, probe.set_homing_current(true));
  home_delta();
  TERN_(SENSORLESS_HOMING, probe.set_homing_current(false));
  endstops.not_homing();
}
```

This seems wrong to me...  SENSORLESS_HOMING has nothing to do with having a probe...

Seems like it should be 

```CPP
void ac_home() {
  endstops.enable(true);
  TERN_(SENSORLESS_PROBING, probe.set_homing_current(true));
  home_delta();
  TERN_(SENSORLESS_PROBING, probe.set_homing_current(false));
  endstops.not_homing();
}
```

Certainly compiles now

Give this a try

**Comment by ellensp** [comment]
This is a marlin issue though, not a config issue...

**Comment by ellensp** [comment]
Seems to have been introduced here https://github.com/MarlinFirmware/Marlin/pull/21899

**Comment by ellensp** [comment]
I've created a PR to fix this issue, since this is not a issue with the Configuration files I am closing this issue.. But the fix should be applied to marlin shortly.
