### ISSUE TITLE
[BUG] (maybe?) HOLLOW_FRAME not possible with RepRapDiscount FULL GRAPHIC Smart Controller?

### ISSUE THREAD

**Issue by Careless** [MarlinFirmware/Configurations#585]
I have the RepRapDiscount FULL GRAPHIC Smart Controller on a printer. Everything seems to work fine in the latest bugfix-2.0 as of Oct 7.

Just wondering how to invert menu selections so that instead of just two horizontal lines above and below the menu item, I would like to have the entire row lit up with the text inverted.

I read about some references to this as the option I need to enable, but it seems that MARLINUI_U8GLIB is not utilized when enabling this specific display, therefore the hollow-frame feature is not activated?

`#if HAS_MARLINUI_U8GLIB || IS_DWIN_MARLINUI
... // Enable to save many cycles by drawing a hollow frame on Menu Screens
#define MENU_HOLLOW_FRAME`

I have the `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` line uncommented and the display is working, it just seems like the inverted selection rows are not.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by thinkyhead** [comment]
> therefore the hollow-frame feature is not activated?

It is up to the implementer of each display to consider Marlin's display options. However, the hollow frame was created to deal with slow screen updates affecting U8G displays, so most displays don't need a hollow frame option for any practical reason.
