### ISSUE TITLE
SKR v1.4 Turbo + BLTouch 

### ISSUE THREAD

**Issue by ACTHEO** [MarlinFirmware/Configurations#586]
SKR v1.4 Turbo + BLTouch
In this version Marlin settings are not correctly controlling BLTouch. I've been testing several configurations for a long time and none of them solved the problem.

SENDING:M119
Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED
z_probe: TRIGGERED

**Comment by ACTHEO** [comment]
SKR v1.4 Turbo + BLTouch
In this release, Marlin settings are not controlling BLTouch correctly. I've been testing several configurations for a long time and none of them solved the problem.

SENDING:
M119 Status report of
end stop x_min: open
y_min: open
z_min: TRIGGERED
z_probe: TRIGGERED

**Comment by Vertabreak** [comment]
seems to suggest the z endstop / probe logic is inverted you should flip it so that it is open when not triggered.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
