### ISSUE TITLE
Compiled Firmware for Ender 3 Pro with BLTouch & 4.2.7 Board does not work (blue/blank LCD Screen)

### ISSUE THREAD

**Issue by Gunhawk007** [MarlinFirmware/Configurations#588]
<!### Bug Description

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.
[Issue_Config_tested.zip](https://github.com/MarlinFirmware/Configurations/files/7332782/Issue_Config_tested.zip)

If you've made any other modifications describe them in detail here.
I have just followed the instructions to get BLTouch enabed. I am also sure that the problem is even there w/o these modifications using the stock files 

### Steps to Reproduce
1) Compiling the code using VSCode (using Auto Build Marlin Extension) resulted in a successful builld).
   I have used the STM32F103RET6_creality environment (the non-maple one)  
2) Copying the .bin file onto an SD Card. 
3) Insert the SD Card and turn on the printer. LCD screen is lit but empty and does not boot showing the Ender screen. 

When I delete the file and replace it with an old working binary of the firmware from Creality everything works.

**Comment by Gunhawk007** [comment]
This is the FW coming out of the build process:
[firmware-20211012-213446.zip](https://github.com/MarlinFirmware/Configurations/files/7332866/firmware-20211012-213446.zip)

And after completing the print in progress with the Creality Firmware, I have retested this file resulting in a Bluescreen/Blank screen issue. For clarity, I am attaching also the FW I am currently using (from Creality):
[Ender-3 Pro_4.2.7_BLTouch_Marlin2.0.1_V1.1.2_TMC2225.bin.zip](https://github.com/MarlinFirmware/Configurations/files/7334775/Ender-3.Pro_4.2.7_BLTouch_Marlin2.0.1_V1.1.2_TMC2225.bin.zip)

I also opend the issue in the Marlin section as I believe this more being a Firmware related issue than a configuration becasue the configuration leads to a successful build - it is just the binary that is not working on my machine.

**Comment by ellensp** [comment]
Correct. closing this Duplicate.
