### ISSUE TITLE
[FR] Biqu BX Configuration

### ISSUE THREAD

**Issue by Lyteral** [MarlinFirmware/Configurations#589]
### Description

This is a request to add a configuration for the Biqu BX 3D printer

### Configuration Details

* Manufacturer: Biqu / BigTreeTect
* Model: BX
* Motherboard: SKR SKR SE-BX

#### Additional Information

https://github.com/bigtreetech/BIQU-BX/tree/master/Firmware/Marlin-2.0.6-BX/Marlin
https://github.com/looxonline/Marlin

**Comment by InsanityAutomation** [comment]
The problem is the LCD code needs major work. It's a pretty large undertaking...

**Comment by thisiskeithb** [comment]
Biqu is working on this.

**Comment by thisiskeithb** [comment]
See https://github.com/MarlinFirmware/Configurations/pull/604
