### ISSUE TITLE
[FR] Suggestion for default settings for the Creality CR20 Pro

### ISSUE THREAD

**Issue by Sporadius** [MarlinFirmware/Configurations#591]
### Description

Enable #define BABYSTEP_ZPROBE_OFFSET in the configuration_adv by default so the configuration of the Z probe offset is easier. 

### Configuration Details

* Manufacturer: Creality
* Model: CR20 Pro
* Motherboard:

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by thisiskeithb** [comment]
Thanks for the suggestion! See https://github.com/MarlinFirmware/Configurations/pull/592

**Comment by thisiskeithb** [comment]
#592 was merged. Closing.
