### ISSUE TITLE
Hotend temperature reading alarm delay

### ISSUE THREAD

**Issue by fghlw** [MarlinFirmware/Configurations#593]
Dear, 
I am runing Marlin , Thermocouple as hotend sensor. But I found that during power on, the first several reading will with errs:  data error or error status. I set mintemp to -9999 can get start sucessful and work. set "THERMOCOUPLE_MAX_ERRORS 50" but seems this only works on serial?  if possible that add a delay for temperayture alarm, that just alarm only never get good result during this "delay time(times)". 
Thank you

**Comment by ellensp** [comment]
you could try  IGNORE_THERMOCOUPLE_ERRORS

**Comment by fghlw** [comment]
yes, but this still will close all necessary alarm, set to -9999 at least max alarm can work. and a delay for some non-immediately alarm is normal option. just an advice for this.

**Comment by thinkyhead** [comment]
Try:
```cpp
#define BOGUS_TEMPERATURE_GRACE_PERIOD 2000 // (ms)
```
If 2000 is too little time, try increasing the value until the error (hopefully) goes away.

**Comment by fghlw** [comment]
ok, Thank you
works

**Comment by fghlw** [comment]
works that add "BOGUS_TEMPERATURE_GRACE_PERIOD"
