### ISSUE TITLE
Nozzle position during filament change right on top of heated bed cable (stock CR-10S)

### ISSUE THREAD

**Issue by juanmacuevas** [MarlinFirmware/Configurations#61]
I'm running marlin 2.0 on a stock CR-10S and I find the **Y position** during filament change dangerous as it melts plastic directly above the bed cable conector and not on the glass. I would suggest changing this value to
`  #define NOZZLE_PARK_POINT { (X_MIN_POS + 3), (Y_MIN_POS + 3), 10 }`
unless... there's a reason behing this I'm missing.

https://github.com/MarlinFirmware/Configurations/blob/4ad76c4f7f0d553e57a89afa307641a67ac51df6/config/examples/Creality/CR-10S/Configuration.h#L1502

**Comment by thinkyhead** [comment]
The CR-10 uses a bigger inset, so I've just now applied that to the CR-10S for consistency.
