### ISSUE TITLE
[BUG] (Ender 5 configuration)

### ISSUE THREAD

**Issue by axpaul** [MarlinFirmware/Configurations#615]
### Configuration Files

I'm trying to make a new marlin software for the 4.2.7 card on my Ender 5, I removed the previous 1.1 in which I had made a marlin software for the bltouch. I have always used VS Code to generate my files and it works pretty well. Currently, I try to use the default configuration files for the 4.2.7 card provided without making any changes. I get an error message telling me that these files are for an older marlin without details - "Your Configuration.h file is for an old version of Marlin. Downgrade Marlin or upgrade your Configuration.h.".

**Actual behavior:**

Currently I can't build marlin for the 4.2.7 board for the Ender 5

**Comment by ellensp** [comment]
You download the wrong version of Config files for the code you are using
See the readme in https://github.com/MarlinFirmware/Configurations (scroll down)

**Comment by ellensp** [comment]
look in Marlin/src/inc/Version.h at SHORT_BUILD_VERSION and MARLIN_HEX_VERSION this is the version of Marlin code you are using

**Comment by ellensp** [comment]
Also config/README.md  will tell you what code and configs you should use

**Comment by axpaul** [comment]
That's right! 
It works now, thank you !
