### ISSUE TITLE
babystepping doesn't work

### ISSUE THREAD

**Issue by pyrophilus** [MarlinFirmware/Configurations#630]
### Bug Description

Babystepping on Z-axis doesn't work

### Configuration Files

No modification.  I have compiled the creality Ender 3V2 example configuration.h and configuration_adv.h with no modification and the compiled firmware will show z-babystepping available, but turning the knob does nothing.

### Steps to Reproduce

1. compile default example configurations for Ender 3V2
2. start a print, press the config icon, and then scroll to Z-offset, select.  Then turning knob does not change z-height.
3. Or, go to, "prepare", then "z-probe wizard", then "move Z to home", then select Z-probe offset, turn knob, no change in z-height.

**Expected behavior:**

When doing #3 from above, the z-height should change, so that I can have a piece of paper underneath and set the z-height.
This worked on all previous versions before 2.0.x.  I have tried the nighly bugfix as well and it still does not work.
I have tried two other firmwares (jyres and mriscoc) that is based on nightly builds and their configurations seem to work.
I have looked at the configuration.h and configuration_adv.h and tried to compare it to the jyers and mriscoc and I can't see what is different, but the configuration.h for the 2.0.9.2 release and nightly bugfixes all seem to not work.

#### Additional Information

I have found multiple cases of people reporting this issue.  On some of them, the issue is referred to an existing open bug report, which has no solution but is closed due to inactivity, or in some of them, the advice is to try the bugfix.  I am writing this because on the latest bugfix the issue still persists.

**Comment by tome9111991** [comment]
You need to enable babystep in config_adv
I use :

```c++
#define BABYSTEPPING
#if ENABLED(BABYSTEPPING)
  //#define INTEGRATED_BABYSTEPPING         // EXPERIMENTAL integration of babystepping into the Stepper ISR
  #define BABYSTEP_WITHOUT_HOMING
  #define BABYSTEP_ALWAYS_AVAILABLE       // Allow babystepping at all times (not just during movement).
  //#define BABYSTEP_XY                     // Also enable X/Y Babystepping. Not supported on DELTA!
  #define BABYSTEP_INVERT_Z false           // Change if Z babysteps should go the other way
  //#define BABYSTEP_MILLIMETER_UNITS       // Specify BABYSTEP_MULTIPLICATOR_(XY|Z) in mm instead of micro-steps
  #define BABYSTEP_MULTIPLICATOR_Z  1       // (steps or mm) Steps or millimeter distance for each Z babystep
  #define BABYSTEP_MULTIPLICATOR_XY 1       // (steps or mm) Steps or millimeter distance for each XY babystep

  #define DOUBLECLICK_FOR_Z_BABYSTEPPING    // Double-click on the Status Screen for Z Babystepping.
  #if ENABLED(DOUBLECLICK_FOR_Z_BABYSTEPPING)
    #define DOUBLECLICK_MAX_INTERVAL 1250   // Maximum interval between clicks, in milliseconds.
                                            // Note: Extra time may be added to mitigate controller latency.
    //#define MOVE_Z_WHEN_IDLE              // Jump to the move Z menu on doubleclick when printer is idle.
    #if ENABLED(MOVE_Z_WHEN_IDLE)
      #define MOVE_Z_IDLE_MULTIPLICATOR 1   // Multiply 1mm by this factor for the move step size.
    #endif
  #endif
//#define BABYSTEP_DISPLAY_TOTAL          // Display total babysteps since last G28

  #define BABYSTEP_ZPROBE_OFFSET          // Combine M851 Z and Babystepping
  #if ENABLED(BABYSTEP_ZPROBE_OFFSET)
    //#define BABYSTEP_HOTEND_Z_OFFSET      // For multiple hotends, babystep relative Z offsets
    //#define BABYSTEP_ZPROBE_GFX_OVERLAY   // Enable graphical overlay on Z-offset editor
  #endif
#endif
```
