### ISSUE TITLE
[Issue] Display malfunction when multiple temperature sensors are used

### ISSUE THREAD

**Issue by RyhthrE-RE** [MarlinFirmware/Configurations#643]
Broad: FlyF407ZG
Display: MKS MINI12864 V3.0
I was thinking building a new printer with FlyF407ZG broad, which has 8 temperature sensor plugs on-board. But when I define more than 5 sensors, the LCD can't show all the readings at status screen. 
![1640776331624](https://user-images.githubusercontent.com/84738876/147658877-103cac34-acd4-40bb-b739-b1c6dc85754b.jpg)

I was thinking display them by some numbers rather than images. Or scroll the readings every certain time.
I'm struggled to solve this problem, what can I do?
BTW, I modified the Marlin 2.0.9.1 Firmware in order to use MKS Mini12864 V3 LCD display, which is the only spare LCD I have...The firmware I use is provided as below.
[ConfigFiles.zip](https://github.com/MarlinFirmware/Configurations/files/7788691/ConfigFiles.zip)

**Comment by ellensp** [comment]
lcd is only 128 pixels across.  
8 hotends is a big ask....
16 pixels per extruder
4 chars each tempature, thats is a 3pixel font (+1 pixel inter char spacer)

**Comment by RyhthrE-RE** [comment]
> How about just numbers？Shows the sensor Type and readings Only.

T1 20°    T4  210°  TB 60°
T2 19°    T5  245°  TC 40°
T3 190°  T6  200° 

That way may save some pixels?

**Comment by descipher** [comment]
Nope. But you could try to workout a left to right scrolling function.

**Comment by thisiskeithb** [comment]
At one point, thinkyhead discussed possibly swapping out extruders on each screen update or disabling graphics for inactive hotends.

Also, this isn’t a bug/feature request for the configuration repo. Please open a Feature Request in the [main Marlin repo](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=T%3A+Feature+Request&template=feature_request.yml&title=%5BFR%5D+%28feature+summary%29).
