### ISSUE TITLE
CUSTOM_STATUS_SCREEN_IMAGE

### ISSUE THREAD

**Issue by Javi3rV** [MarlinFirmware/Configurations#654]
### Bug Description

Error while compiling:
"CUSTOM_STATUS_SCREEN_IMAGE requires a 128x64 DOGM B/W Graphical LCD."

I just want to use the default marlin screen on Anet A8.
### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.
[Marlin.zip](https://github.com/MarlinFirmware/Configurations/files/7838429/Marlin.zip)
If you've made any other modifications describe them in detail here.

I made some minimal changes, activated CUSTOM_STATUS_SCREEN_IMAGE line, nothing else related to Statusscreen.h, everything as default.

### Steps to Reproduce

1. [Extract files from my ZIP]
2. [Put them in Marlin folder]
3. [Open marlin.ino with arduino IDE 1.8.19 and try to compile it]

**Expected behavior:**
It should compile, but I dont know what does that error mean.

**Actual behavior:**
It returns error "CUSTOM_STATUS_SCREEN_IMAGE requires a 128x64 DOGM B/W Graphical LCD."

**Comment by ellensp** [comment]
You have ZONESTAR_LCD enabled
This is a 20x4 character display
You cannot have graphics on a character display

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
