### ISSUE TITLE
Incorrect driver type for Ender3 V2 4.2.2 in Marlin 2.0.9.3

### ISSUE THREAD

**Issue by r0dnay** [MarlinFirmware/Configurations#661]
hi,

im having the same issue as the OP in this thread
https://github.com/MarlinFirmware/Configurations/issues/638

> The 4.2.2 comes with 5 different stepper driver types There is no way to detect this. You have you physically look at your controller for the hand written letter written on the sdcard cover. It will be one of these letters C = HR4988 E = A4988 A = TMC2208 B = TMC2209 H = TMC2225 Thus you get an warning "Check your board and make sure to select the correct DRIVER_TYPE!"
> 
> The board not booting is unrelated to this. There was an issue with 2.0.9.3 and bugfix that stopped most boards starting up. This has been resolved Get a fresh copy of 2.0.9.3. and try again

any idea where DRIVER_TYPE is defined?

also, my sdcard covers are D on one printer and E on another, is there a D missing from yor list? i saw the same list just now on TH3D, cant seem to find anywhere which tells you which driver to use for 'D' 

thanks

**Comment by ellensp** [comment]
This Issue Queue is for Marlin confiig bug reports, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by ellensp** [comment]
A "D" is probably a A, written by a non english speaker in a rush as they have several million do to.
