### ISSUE TITLE
[BUG] Ender 3 4.2.7 config doesnt work in default

### ISSUE THREAD

**Issue by T0biasCZe** [MarlinFirmware/Configurations#667]
### Bug Description
The example code for Ender 3 with 4.2.7/4.2.2 motherboard doesnt compile without modifying the example configuration

### Steps to Reproduce
Download Marlin 2.0.9.3
Download these example files
copy over the Ender 3 4.2.7 or 4.2.2 config files
Open the marlin folder in 

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

The firmware compiles correctly with the unmodified example config

**Actual behavior:**

The compile throws
```
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2002:6: error: #error "FAN_SOFT_PWM is required. Enable it to continue."
 2002 |     #error "FAN_SOFT_PWM is required. Enable it to continue."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:30:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2002:6: error: #error "FAN_SOFT_PWM is required. Enable it to continue."
 2002 |     #error "FAN_SOFT_PWM is required. Enable it to continue."
      |      ^~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2002:6: error: #error "FAN_SOFT_PWM is required. Enable it to continue."
 2002 |     #error "FAN_SOFT_PWM is required. Enable it to continue."
      |      ^~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
```

**Comment by thisiskeithb** [comment]
Enable / uncomment `FAN_SOFT_PWM` for now.

**Comment by T0biasCZe** [comment]
Yeah i uncommented it and it compiled... Tho i put the bin on the sd card, it loaded the firmware but it cant auto home... it returns PRINTER HALTED... _should i create separate issue for this?_

**Comment by ellensp** [comment]
Check you really have a 4.2.7, installing 4.2.7 firmware on a 4.2.2 machine results in it looking like everything is fine, but no steppers move.

**Comment by T0biasCZe** [comment]
Oops yeah its 4.2.2... i incorrectly looked
