### ISSUE TITLE
Tronxy X5S for BTT SKR2 with TMC2209 

### ISSUE THREAD

**Issue by nicken83** [MarlinFirmware/Configurations#668]
I'm having a really hard time configuring Marlin to this setup. Tried several compilations, always only diagonal movement in X and Y.
CoreXY is `defined`

<!--Tronxy x5s for BTT Skr2 with Te MC 2209 --

**Comment by ellensp** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/issues/23570
