### ISSUE TITLE
new to 3d printing

### ISSUE THREAD

**Issue by Mr-Mad-Watch** [MarlinFirmware/Configurations#670]
just got and Ender 3 Pro with the 4.2.2 32 bit motherboard and this is what shows up while im trying to get the firmware ready to flash the printer.i have no experience with this stuff. i need a little guidance if its possible please.

 #elif ENABLED(FAN_SOFT_PWM_REQUIRED) && DISABLED(FAN_SOFT_PWM)
    #error "FAN_SOFT_PWM is required. Enable it to continue."
  #endif

**Comment by ellensp** [comment]
So Enable FAN_SOFT_PWM
This is already fixed in Bugfix Configs,
