### ISSUE TITLE
[BUG] Steps only once per-direction with Dual E-Steppers

### ISSUE THREAD

**Issue by mpheyse** [MarlinFirmware/Configurations#678]
### Bug Description

> PLEASE NOTE: this can be confusing Terminology. I'm adding a second duplicate E0 drive motor (_extruder_) to the Filament path. I'm not adding a Second E1 extruder for a second Filament. We've upgraded from a remote_drive-Bowden_Tube, configuration to a Direct Drive with a light weight motor on the moving head. This improved our print quality, but the light weight motor is struggling to pull from a 20lb not-well wound spool consistently.  so we want a Second mirrored E0 motor to pull the filament to the printer, leaving the light weight to only run the hotend pressure. To do this we are simple reactivating the original remote drive motor (larger more torque), with a free-space loop prior to entering the printer

After adding a fifth Driver chip, connecting the printer's original E-motor to it.

Enabling E_DUAL_STEPPER_DRIVERS

And Setting a proper E1 driver. (The Manual says NOT to do this when Dualing X, unfortunately it says NOTHING about dualing E)

With the motors in free space (no filament)

the second E0 motor (e1) will only turn for the first movement (load) command,  all proceeding moves gives a loud buzzing nose with no movement.  Swapping the E motors just moves the problem. Reversing the direction (un-load) will give one more movement in the unload direction, then buzzing.

### Configuration Files
[CONF.ZIP](https://github.com/MarlinFirmware/Configurations/files/8064932/CONF.ZIP)

Changes from single E0 motor Setup

Configuration_adv.h
#define E_DUAL_STEPPER_DRIVERS //Enabled

  #if AXIS_IS_TMC(E1)
    #define E1_CURRENT      400 //Current limit same as E0

Configuration.h
#define E1_DRIVER_TYPE TMC2209 //Same as E0

### Steps to Reproduce

From a Working single E stepper setup, 
add a second E motor
add a second Extruder (gear set)
add a fifth (second E) driver

Enable E_DUAL_STEPPER_DRIVERS in Configuration_adv.h

Optionally 
Set Current limit for E1 same as E0
Set Driver for E1 same as E0 (they are the same driver module model)

**Expected behavior:**

Both motors to move in step, and as both have the same Extruder gear set the Filament should move the same.

There to be a guide on doing this somewhere or the Manual to cover what else needs to be configured with  E_DUAL_STEPPER_DRIVERS enabled

**Actual behavior:**
With no filament loaded

On the 10mm setting, the stepper connected to E0, will move properly, E1 (port) motor will only move once per direction, and make a buzzing noise otherwise.

Swapping motor ports between the motors, moves the issue to the motor that's plugged in to the E1 port

#### Additional Information
Marlin 2.0.x
Bigtree SKR 1.4 Turbo
Bigtree TFT 35 E3 V3.0
Sunlu S8 (Ender 3 clone)
Bigtree TMC2209 drivers for all steppers (dual-z share a stepper driver with higher current setting)

Both motors work in the original port E0 just fine.

Drivers are set up the same in the MB, each with the pin clipped (this is not a skr 2.0)

First attempt didn't have #define E1_DRIVER_TYPE TMC2209 defined (like what Dual_X says) and I thought that was the issue, but defining it didn't help.

> Edit: Overnight I had the Idea that the new driver (TMC2209) might be bad as its the only equipment (other than the fifth port on the MB) that has not previously been used. Swapping the forth (known good) driver with the fifth (new) didn't change anything. The same problem exits on what ever motor is plugged into the E1 (second E0) Port.

If it's something stupid, and I just missing it, I apologize in advance. I did RTFM and it didn't help.

**Comment by ellensp** [comment]
This github is for issue and requests pertaining to provided configuration examples. not for support requests

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
