### ISSUE TITLE
x, y axis issue while leveling Ender 3 , SKR mini e3 v1.2

### ISSUE THREAD

**Issue by Stieges** [MarlinFirmware/Configurations#68]
The X and Y Axis are making noises while bed leveling. Also the y-axis does not move properly (it does not move at all). Custom movements are no problem.
 I tried the "old" bin file and the printer is not the problem.
Also the x and y axis size is wrong i think. it is 220 and not 235. But this was not the reason for the strange behaviour.

**Comment by thinkyhead** [comment]
We rely on vendors and experienced owners of machines to provide the best configurations from their experience. If you have a better working configuration please submit it. You may want to discuss it with others in the Ender 3 user group so that you all agree on the correct settings.
