### ISSUE TITLE
[FR] BL Touch upgrade for the Artillery Hornet 

### ISSUE THREAD

**Issue by afruzu** [MarlinFirmware/Configurations#680]
Good morning, sorry I'm a new Github user and don't know well how to operate correctly.
II would like to ask you to consider the BL Touch upgrade for the Artillery Hornet printer among the Marlin configuration examples.
Based on previous files available on Thinghiverse, I have developed configuration files for version 2.0.9.1 that I would like to send you as a starting point in the attached zip file. these files give rise to a configuration that works perfectly with Marlin 2.0.9.1.
I tried to adapt them for the current version 2.0.9.3 of Marlin but the compilation ends in an error that I cannot solve. 
Thank you

### Configuration Details

<!-- Please describe the hardware/configuratio
[Artillery.Hornet.BLTouch.upgrade.zip](https://github.com/MarlinFirmware/Configurations/files/8103672/Artillery.Hornet.BLTouch.upgrade.zip)

* Manufacturer: Artillery
* Model: Hornet 
* Motherboard:

#### Additional Information

* Provide links to the requested printer/configuration.

**Comment by thinkyhead** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
