### ISSUE TITLE
[BUG] Creality Ender-3 Pro BigTreeTech SKR Mini E3 3.0 do not compile

### ISSUE THREAD

**Issue by fabricioncosta** [MarlinFirmware/Configurations#684]
<!--

### Bug Description

Ender-3 PRO config file for the SKR Mini E3 3.0 do not compile. Error: Marlin\src\lcd\marlinui.cpp:774:61: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?

### Configuration Files

[BigTreeTech SKR Mini E3 3.0.zip](https://github.com/MarlinFirmware/Configurations/files/8147755/BigTreeTech.SKR.Mini.E3.3.0.zip)

### Steps to Reproduce

1. Put the file on the right place.
2. Use the same version 02000903 of marlin.
3. Compile

**Expected behavior:**

Bin file generated.

**Actual behavior:**

Compilation error: Marlin\src\lcd\marlinui.cpp:774:61: error: 'manual_feedrate_mm_s' was not declared in this scope; did you mean 'feedrate_mm_s'?

#### Additional Information

NA.

**Comment by ellensp** [comment]
github seems to be eating posts 

Error from offiginal post
"Marlin\src\lcd\marlinui.cpp:774:61: error: 'manual_feedrate_mm_s' was not"

This is a user error.
You downloaded import branch configs 

You must download the version of configs that matches your code version.

Either bugfix-2.0.x branch or release-2.0.x.x

**Comment by fabricioncosta** [comment]
Hi ellensp, thanks for your help. 

It works with marlin and configuration in bugifx2.0.x.  I have tested all these combination:

Configuration | Marlin | Result

import-2.0.x   |  2.0.x              | Same error
bugfix-2.0.x    |  2.0.x              | Same error
release-2.0.9.3|  XX                 | config files for BigTreeTech SKR Mini E3 3.0 do not exist
bugfix-2.0.x     |  bugfix-2.0.x  | Success!! (not tested in the printer yet)

Thanks!

Fabrício
