### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by cmclellan89** [MarlinFirmware/Configurations#699]
Hello I'm a new user trying to update my firmware in workspace, I keep getting 61 "function call is not allowed in a constant expression". I first tried to look on Youtube to figure out how to fix the issues but nothing has help.

"function call is not allowed in a constant expression C/C++(59)"

**Comment by Vertabreak** [comment]
not enough data presented suggest the posting of complete error logs and configs used along with what type of system your working with so we can see if your missing dependency's for example. the more data presented the greater our understanding of what is happening will be, simply saying its broken or something does not work is not productive at all.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
