### ISSUE TITLE
BIGTREETECH SKR MINI E3 V3.0 Ender 3 pro

### ISSUE THREAD

**Issue by Nico4589** [MarlinFirmware/Configurations#701]
Hi, I have an ender 3 pro with a BIGTREETECH SKR MINI E3 V3.0 board. But in the configurations of Marlin there are only previous versions. How can I get the right configuration for my 3d printer?

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
