### ISSUE TITLE
 Ender 3 pro, BIGTREETECH SKR MINI E3 V3.0 Marlin 2.0.9.3

### ISSUE THREAD

**Issue by Nico4589** [MarlinFirmware/Configurations#702]
Hi, I have an ender 3 pro with a BIGTREETECH SKR MINI E3 V3.0 board. I have installed the latest version of Marlin (2.0.9.3). Which configurations should I use? Thank you

**Comment by ellensp** [comment]
For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
