### ISSUE TITLE
[FR] Artillery Hornet + BLTouch configs

### ISSUE THREAD

**Issue by afruzu** [MarlinFirmware/Configurations#708]
### Are you looking for hardware support?

Good morning, sorry I'm a new Github user and don't know well how to operate correctly. 
II would like to ask you to consider the BL Touch upgrade for the Artillery Hornet printer among the Marlin configuration examples.
Based on previous files available on Thinghiverse, I have developed configuration files for version 2.0.9.1 that I would like to send you as a starting point. I tried to adapt them for the current version 2.0.9.3 of Marlin but the compilation ends in an error that I cannot solve.
Thank you
[Artillery Hornet BLTouch upgrade.zip](https://github.com/MarlinFirmware/Marlin/files/8103637/Artillery.Hornet.BLTouch.upgrade.zip)
 

### Describe the feature you want

Adding a configuration for BL Touch on Artillery Hornet Printer

**Comment by thinkyhead** [comment]
Duplicate of #649
