### ISSUE TITLE
information more than Issue Athorbot buddy

### ISSUE THREAD

**Issue by mattthhdp** [MarlinFirmware/Configurations#71]
I just got my hand on an Athorbot buddy, and the firmware really suck ... (not intuitive, not been able to change filament and so on .... the list is pretty long)

on the website ... the only thing i can download is the .hex to flash the firmware, but it's pretty hold.

Anyone know if it's possible to flash the marlin firmware on this 3d printer ?
i have looked into the exemple rep on github, and the 3d printer is not listed, now i know it do not mean that it doesn't work but it better to ask before and not after !^^

**Comment by thinkyhead** [comment]
This Issue Queue is for development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
