### ISSUE TITLE
[FR] Set bugfix-2.0.x branch as default

### ISSUE THREAD

**Issue by thisiskeithb** [MarlinFirmware/Configurations#715]
### Feature Request Description

Can the `bugfix-2.0.x` branch be set as default for this repo?

Despite our best efforts to prevent compiling with the `import-2.0.x` branch, users are still trying to run it due to it being the default branch when visiting this repo.

The only “issue” is that developers would need to target the correct branch when submitting PRs, but we that’s already expected in the main Marlin repo and we have a bot to handle PRs pointed at the incorrect branch with instructions.

**Comment by thisiskeithb** [comment]
Also, is https://github.com/MarlinFirmware/Configurations/tree/master used at all? That can probably get purged.

**Comment by berkeoznalbant** [comment]
Yeah, I accidentally used import branch when I bought a new skr board. I was just learning how to compile and flash firmware.

**Comment by thinkyhead** [comment]
It would make slightly more sense to have a branch called "release" as the default, and have it aliased to the current release.
