### ISSUE TITLE
'PE_MAGNET_ON_STATE' was not declared in this scope

### ISSUE THREAD

**Issue by Nico4589** [MarlinFirmware/Configurations#717]
Why do I get this error message when I activate #define EXT SOLENOID ('PE_MAGNET_ON_STATE' was not declared in this scope)? I have configured the SOL0_PIN pin on a fan.

**Comment by ellensp** [comment]
This Issue Queue is for Marlin configuration bug reports, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by Nico4589** [comment]
But I think it's a bug

**Comment by ellensp** [comment]
"After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose)."
