### ISSUE TITLE
Anet A8 Plus error: missing binary operator before token "(" 

### ISSUE THREAD

**Issue by voxpatriam** [MarlinFirmware/Configurations#722]
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:83:51: error: missing binary operator before token "(" 
   83 | #define AXIS_DRIVER_TYPE(A,T) AXIS_DRIVER_TYPE_##A(T)

I get this error every time I try to compile my firmware. I know absolutely nothing about coding but have used Marlin for a few years by following guides. A little help please and thank you!

[Marlin.zip](https://github.com/MarlinFirmware/Configurations/files/8599110/Marlin.zip)

**Comment by ellensp** [comment]
This is not a support forum

This Issue Queue is for Marlin example Configurations bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report]

In saying that only thing wrong with config is you have #define ENDSTOP_INTERRUPTS_FEATURE, but the skr 1.4 cannot do this.
Also  MICROSTEPS  are also at 64, which is pointless on a 3d printer, doubbly so when you have define INTERPOLATE true
