### ISSUE TITLE
There are no example configuration files for Marlin 2.1 -- #define CONFIGURATION_H_VERSION 02010000

### ISSUE THREAD

**Issue by BigBird0000** [MarlinFirmware/Configurations#740]
### Bug Description

Configuration files are not available for Marlin  #define CONFIGURATION_H_VERSION 02010000
(downloaded from github 2022-0-5-24)

### Configuration Files
no files to download

### Steps to Reproduce

no files on github
**Expected behavior:**
There should be example configuration files for Marlin 2.1 -- #define CONFIGURATION_H_VERSION 02010000

**Actual behavior:**

No FIles Available

#### Additional Information

![image](https://user-images.githubusercontent.com/15950085/170302740-5bda378b-f67c-4cac-83d6-d8f3a142c299.png)

**Comment by cp2004** [comment]
https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x

**Comment by BigBird0000** [comment]
Thank you Charlie!
