### ISSUE TITLE
[BUG] compilation fails for Two Trees Bluer Plus with mks_robin_nano35_maple

### ISSUE THREAD

**Issue by Stefan-van-Hattum** [MarlinFirmware/Configurations#742]
### Bug Description

Downloaded latest Marlin 2.0.9.3 and the configurations file 2.0.9.3
After making the following modifications according to YouTube channel Aurora Tech:

#define Z_MIN_ENDSTOP_INVERTING false// Set to true to invert the logic of the endstop.

// XPT2046 Touch Screen calibration
#define TOUCH_CALIBRATION_X 16903
#define TOUCH_CALIBRATION_Y 10346
#define TOUCH_OFFSET_X        -25
#define TOUCH_OFFSET_Y        -22

I saved the config and try to build using mks_robin_nano35_maple.
The following is shown:

> Executing task: C:\Users\Stefan\.platformio\penv\Scripts\platformio.exe run --environment mks_robin_nano35_maple <

Processing mks_robin_nano35_maple (board: genericSTM32F103VE; platform: ststm32@~12.1; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103VE.html
PLATFORM: ST STM32 (12.1.1) > STM32F103VE (64k RAM. 512k Flash)       
HARDWARE: STM32F103VET6 72MHz, 64KB RAM, 512KB Flash
DEBUG: Current (jlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32-maple @ 3.10000.201129 (1.0.0)
 - tool-stm32duino @ 1.0.2
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
Converting Marlin.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- SoftwareSerialM @ 1.0.0
|-- STM32ADC @ 1.0
|-- EEPROM
|-- USBComposite for STM32F1 @ 0.99
|-- Wire @ 1.0
|-- Servo(STM32F1) @ 1.1.2
Building in release mode
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\board.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\wirish\boards.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\wirish\boards_setup.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\wirish\start.S.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\wirish\start_c.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduinoVariant\wirish\syscalls.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\HardwareTimer.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\Print.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\WString.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\avr\dtostrf.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\cxxabi-compat.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\ext_interrupts.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\hooks.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\itoa.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\adc.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\adc_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\bkp_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\dac.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\dma.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\dma_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\exc.S.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\exti.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\exti_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\flash.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\fsmc_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\gpio.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\gpio_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\i2c.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\i2c_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\iwdg.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\nvic.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\pwr.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\rcc.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\rcc_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\spi.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\spi_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\stm32f1\performance\isrs.S.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\stm32f1\performance\vector_table.S.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\systick.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\timer.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\timer_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usart.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usart_f1.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usart_private.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\stm32f1\usb.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\stm32f1\usb_cdcacm.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\stm32f1\usb_reg_map.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\usb_lib\usb_core.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\usb_lib\usb_init.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\usb_lib\usb_mem.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\usb\usb_lib\usb_regs.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\libmaple\util.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\main.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\new.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\pwm.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\sdio.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\stm32f1\util_hooks.c.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\stm32f1\wiring_pulse_f1.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\stm32f1\wirish_debug.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\stm32f1\wirish_digital_f1.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\tone.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\usb_serial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\wirish_analog.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\wirish_digital.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\wirish_math.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\wirish_shift.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\FrameworkArduino\wirish_time.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\HAL.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\HAL_SPI.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\MarlinSerial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\MinSerial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\SPI.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\Servo.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\dogm\u8g_com_stm32duino_swspi.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\eeprom_bl24cxx.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\eeprom_flash.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\eeprom_if_iic.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\eeprom_sdcard.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\eeprom_wired.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\fast_pwm.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\msc_sd.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\onboard_sd.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\sdio.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\tft\tft_fsmc.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\tft\tft_spi.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\tft\xpt2046.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\timers.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\STM32F1\watchdog.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\Delay.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\HAL.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\MinSerial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\eeprom_api.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\esp_wifi.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\HAL\shared\servo.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\MarlinCore.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\core\serial.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\core\utility.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\babystep.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\bedlevel\abl\bbl.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\bedlevel\bedlevel.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\bltouch.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\hotend_idle.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\pause.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\powerloss.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\feature\runout.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\bedlevel\G42.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\bedlevel\M420.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\bedlevel\abl\G29.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\bedlevel\abl\M421.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\calibrate\G28.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M200-M205.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M220.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M221.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M301.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M302.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M304.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M309.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\config\M92.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M108_M112_M410.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M111.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M120_M121.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M17_M18_M84.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M211.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M280.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M400.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M80_M81.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M85.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M993_M994.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M997.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\M999.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\control\T.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\eeprom\M500-M504.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\digipot\M907-M910.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\pause\G27.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\pause\M125.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\pause\M600.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\pause\M603.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\pause\M701_M702.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\powerloss\M1000.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\powerloss\M413.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\feature\runout\M412.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\gcode.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\gcode_d.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\geometry\G92.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\geometry\M206_M428.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M110.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M113.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M114.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M115.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M118.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\host\M119.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\lcd\M0_M1.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\lcd\M117.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\lcd\M145.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\lcd\M300.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\lcd\M995.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\motion\G0_G1.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\motion\G2_G3.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\motion\G4.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\motion\M290.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\parser.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\probe\G30.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\probe\M401_M402.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\probe\M851.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\queue.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M1001.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M20.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M21_M22.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M23.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M24_M25.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M26.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M27.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M28_M29.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M30.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M32.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M33.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M34.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M524.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\sd\M928.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\stats\M31.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\stats\M75-M78.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M104_M109.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M105.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M106_M107.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M140_M190.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M141_M191.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M155.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\temp\M303.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\gcode\units\M82_M83.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\inc\Warnings.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_advanced.cpp.o
Marlin\src\inc\Warnings.cpp:602:4: warning: #warning "Maple build environments are deprecated. Please use a non-Maple build environment. Report issues to the Marlin Firmware project." [-Wcpp]
   #warning "Maple build environments are deprecated. Please use a non-Maple build environment. Report issues to the Marlin Firmware project."
    ^~~~~~~
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_bed_corners.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_bed_leveling.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_configuration.cpp.o
Compiling .pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_filament.cpp.o
Marlin\src\lcd\marlinui.cpp: In static member function 'static void ManualMove::task()':
Marlin\src\lcd\marlinui.cpp:796:60: error: 'manual_feedrate_mm_s' was not declared in this scope
         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
                                                            ^~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\marlinui.cpp:796:60: note: suggested alternative: 'feedrate_mm_s'
         const feedRate_t fr_mm_s = (axis < LOGICAL_AXES) ? manual_feedrate_mm_s[axis] : XY_PROBE_FEEDRATE_MM_S;
                                                            ^~~~~~~~~~~~~~~~~~~~
                                                            feedrate_mm_s
Marlin\src\lcd\menu\menu.cpp: In function 'void line_to_z(const_float_t)':
Marlin\src\lcd\menu\menu.cpp:285:30: error: 'manual_feedrate_mm_s' was not declared in this scope
     line_to_current_position(manual_feedrate_mm_s.z);
                              ^~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\menu\menu.cpp:285:30: note: suggested alternative: 'feedrate_mm_s'
     line_to_current_position(manual_feedrate_mm_s.z);
                              ^~~~~~~~~~~~~~~~~~~~
                              feedrate_mm_s
*** [.pio\build\mks_robin_nano35_maple\src\src\lcd\marlinui.cpp.o] Error 1
*** [.pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu.cpp.o] Error 1
Marlin\src\lcd\menu\menu_bed_corners.cpp: In function 'void _lcd_goto_next_corner()':
Marlin\src\lcd\menu\menu_bed_corners.cpp:316:30: error: 'manual_feedrate_mm_s' was not declared in this scope
     line_to_current_position(manual_feedrate_mm_s.x);
                              ^~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\menu\menu_bed_corners.cpp:316:30: note: suggested alternative: 'feedrate_mm_s'
     line_to_current_position(manual_feedrate_mm_s.x);
                              ^~~~~~~~~~~~~~~~~~~~
                              feedrate_mm_s
*** [.pio\build\mks_robin_nano35_maple\src\src\lcd\menu\menu_bed_corners.cpp.o] Error 1
========================================================================================= [FAILED] Took 115.16 seconds =========================================================================================
Environment             Status    Duration
----------------------  --------  ------------
mks_robin_nano35_maple  FAILED    00:01:55.156
==================================================================================== 1 failed, 0 succeeded in 00:01:55.156 ==================================================================================== 
The terminal process "C:\Users\Stefan\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'mks_robin_nano35_maple'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

I also tried using bugfix-2.0.x and the import-2.0.x but these give different errors when building.

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

[configurations.zip](https://github.com/MarlinFirmware/Configurations/files/8793183/configurations.zip)

### Steps to Reproduce

1. Make modifcation in Configuration.h
2. Save modified Configuration.h
3. Use PlatformIO and select mks_robin_nano35_maple
4. click build
5. wait for error to apear

**Expected behavior:**

I expect compilation successful and have a custom Marlin firmware for my Two Trees Bluer Plus.

**Actual behavior:**

Build fails with errors

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by ellensp** [comment]
You did not download Marlin 2.0.9.3 https://github.com/MarlinFirmware/Marlin/archive/refs/tags/2.0.9.3.zip 
You downloaded Marlin 2.0.x ie https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip

2.0.x is slightly ahead of 2.0.9.3 and breaks if you use 2.0.9.3 config files.

In particular In Configuration_adv.h this has changed

 2.0.x needs 
```
// @section lcd

#if HAS_MANUAL_MOVE_MENU
  #define MANUAL_FEEDRATE { 50*60, 50*60, 4*60, 2*60 } // (mm/min) Feedrates for manual moves along X, Y, Z, E from panel
```

Marlin 2.0.9.2 - 2.0.9.3 needs
```
// @section lcd

#if ANY(HAS_LCD_MENU, EXTENSIBLE_UI, HAS_DWIN_E3V2)
  #define MANUAL_FEEDRATE { 50*60, 50*60, 4*60, 2*60 } // (mm/min) Feedrates for manual moves along X, Y, Z, E from panel
```

**Comment by Stefan-van-Hattum** [comment]
Hi ,

Thank you for the response, looking at the website of Marlin it says version 2.0.9.3 but the link is indeed 2.0.x.zip which I didn’t notice.
That is a mistake on the website I guess then.
***@***.***

I will try to download the 2.0.9.3 from github using the link you supplied.
Thank you !.

Regards,

Stefan

Van: ellensp ***@***.***>
Verzonden: Sunday, 29 May 2022 13:17
Aan: MarlinFirmware/Configurations ***@***.***>
CC: Stefan-van-Hattum ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MarlinFirmware/Configurations] [BUG] compilation fails for Two Trees Bluer Plus with mks_robin_nano35_maple (Issue #742)


You did not download Marlin 2.0.9.3 https://github.com/MarlinFirmware/Marlin/archive/refs/tags/2.0.9.3.zip
You downloaded Marlin 2.0.x ie https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip

2.0.x is slightly ahead of 2.0.9.3 and breaks if you use 2.0.9.3 config files.

In particular In Configuration_adv.h this has changes a lot recently

2.0.x needs

// @section lcd



#if HAS_MANUAL_MOVE_MENU

  #define MANUAL_FEEDRATE { 50*60, 50*60, 4*60, 2*60 } // (mm/min) Feedrates for manual moves along X, Y, Z, E from panel

Marlin 2.0.9.2 - 2.0.9.3 needs

// @section lcd



#if ANY(HAS_LCD_MENU, EXTENSIBLE_UI, HAS_DWIN_E3V2)

  #define MANUAL_FEEDRATE { 50*60, 50*60, 4*60, 2*60 } // (mm/min) Feedrates for manual moves along X, Y, Z, E from panel
