### ISSUE TITLE
[BUG] 2.0.9.4 compile errors when number of Z Steppers is > 1

### ISSUE THREAD

**Issue by SwiftNick** [MarlinFirmware/Configurations#746]
**Problem:**
Using the Anycubic Chiron configs (and probably any other config with more than 1 Z Stepper), the build fails with:

`Marlin\src\module\motion.cpp: In function 'void homeaxis(AxisEnum)':
Marlin\src\module\motion.cpp:1902:65: error: 'class Stepper' has no member named 'set_z3_lock'; did you mean 'set_z1_lock'?
               stepper.set_z1_lock, stepper.set_z2_lock, stepper.set_z3_lock
                                                                 ^~~~~~~~~~~
                                                                 set_z1_lock
Marlin\src\module\motion.cpp:1908:52: error: 'class Endstops' has no member named 'z3_endstop_adj'; did you mean 'z2_endstop_adj'?      
               0, endstops.z2_endstop_adj, endstops.z3_endstop_adj
                                                    ^~~~~~~~~~~~~~
                                                    z2_endstop_adj
Marlin\src\module\motion.cpp:1972:21: error: 'class Stepper' has no member named 'set_z3_lock'; did you mean 'set_z1_lock'?
             stepper.set_z3_lock(false);
                     ^~~~~~~~~~~
                     set_z1_lock`

**Cause:**                     
The definition for `NUM_Z_STEPPER_DRIVERS` has been removed from the 2.0.9.4 configs.
In the 2.1.0.0 release, `NUM_Z_STEPPER_DRIVERS` is set automatically in Conditionals_LCD.h [[Line 705]](https://github.com/MarlinFirmware/Marlin/blob/959a6c4f7037345dd6f2bf5abe3c376981988aed/Marlin/src/inc/Conditionals_LCD.h#L705) but this behaviour is not present in 2.0.9.4.

**Solution:**
The quick fix is to add the `#define NUM_Z_STEPPER_DRIVERS 2` definition back in the Configuration_adv.h file.

**Comment by thisiskeithb** [comment]
Please file a bug report in the [main Marlin repo](https://github.com/MarlinFirmware/Marlin/issues/new?assignees=&labels=&template=bug_report.yml&title=%5BBUG%5D+%28bug+summary%29).
