### ISSUE TITLE
Request: Alfawise U20 Plus

### ISSUE THREAD

**Issue by cn-tools** [MarlinFirmware/Configurations#75]
I'm absolutly new on this area.
So firat thx to all, you make a great job.

Maybe i will buy a Alfawise U20 Plus and so it is very interessting for me to know if i can use the 'normal' U20 config? Or did i need an adapted or complitly new config.

In the first step, i think i don't buy the BLtouch. But maybe a few weeks/months in the future ;)

Maybe anybody have a config for the U20 Plus? Would you send a Pull Request please?

Thx again to all for your great job!

Best regards

**Comment by thinkyhead** [comment]
Duplicate of #649
