### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by fludziu** [MarlinFirmware/Configurations#754]
When I want to compile Marlin 2.1 on MKS Robin Nano V3.1 + MKS TS35 display, I am not able to activate FILAMENT_RUNOUT_SENSOR

I have everything activate as in stock Marlin for Sapphire Pro from examples plus some extra features like TMC2209, PWC, BLTOUCH own PID tuning etc...
 
And this last thing which is not working on my 3D printer. As I compared it to the example configuration, there is TFT35 display with deault color ui; but I'm using graphic ui.

Here is the error, which I have:

`Compiling .pio\build\mks_robin_nano_v3_usb_flash_drive\src\src\lcd\extui\mks_ui\[config.zip](https://github.com/MarlinFirmware/Configurations/files/8933612/config.zip).o
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp: In function 'void btn_ok_event_cb(lv_obj_t*, lv_event_t)':
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:137:7: error: 'pause_menu_response' was not declared in this scope; did you mean 'pause_menu_disp'?
  137 |       pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE;
      |       ^~~~~~~~~~~~~~~~~~~
      |       pause_menu_disp
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:137:29: error: 'PAUSE_RESPONSE_EXTRUDE_MORE' was not declared in this scope
  137 |       pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from Marlin\src\lcd\extui\mks_ui\../../../inc/MarlinConfigPre.h:37,
                 from Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:27:
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp: In function 'void btn_cancel_event_cb(lv_obj_t*, lv_event_t)':
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:189:35: error: 'pause_menu_response' was not declared in this scope; did you mean 'pause_menu_disp'?
  189 |     TERN_(ADVANCED_PAUSE_FEATURE, pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT);
      |                                   ^~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:245:29: note: in expansion of macro '_TERN'
  245 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                             ^~~~~
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:189:5: note: in expansion of macro 'TERN_'
  189 |     TERN_(ADVANCED_PAUSE_FEATURE, pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT);
      |     ^~~~~
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:189:57: error: 'PAUSE_RESPONSE_RESUME_PRINT' was not declared in this scope
  189 |     TERN_(ADVANCED_PAUSE_FEATURE, pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:621:26: note: in definition of macro 'THIRD'
  621 | #define THIRD(a,b,c,...) c
      |                          ^
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:247:29: note: in expansion of macro '___TERN'
  247 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:246:29: note: in expansion of macro '__TERN'
  246 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/8933609/Configuration.zip)
^~~~~~
Marlin\src\lcd\extui\mks_ui\../../../inc/../core/macros.h:245:29: note: in expansion of macro '_TERN'
  245 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
Marlin\src\lcd\extui\mks_ui\draw_dialog.cpp:189:5: note: in expansion of macro 'TERN_'
  189 |     TERN_(ADVANCED_PAUSE_FEATURE, pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT);
      |     ^~~~~
*** [.pio\build\mks_robin_nano_v3_usb_flash_drive\src\src\lcd\extui\mks_ui\draw_dialog.cpp.o] Error 1`

**Comment by thisiskeithb** [comment]
Please file a proper bug report in the main Marlin Firmware repo: https://github.com/MarlinFirmware/Marlin
