### ISSUE TITLE
Marlin 2.1.x bugfix have bug surface move on delta it curve like palabolic cant print

### ISSUE THREAD

**Issue by flishy2532** [MarlinFirmware/Configurations#778]
Marlin 2.1.x bugfix have bug surface move on delta it curve like palabolic cant print

am use mainboard MKS TINYBEE and test  on marlin 2.1.x bugfix cant print because have bug move axis x and y curve like palabolic am try test all marlin it fix by marlin 2.1 

https://github.com/MarlinFirmware/Marlin/archive/2.1.zip

https://github.com/MarlinFirmware/Configurations/tree/release-2.1

on this link 

This My FirmWare FIX LayerShift and FIX bug surface move on AnyCubic Kossel Linear Plus

https://drive.google.com/file/d/1ul_R1qhKv85zVdQV6JqzSsqLfH8LV5lW/view?usp=sharing

EXE FILE

https://drive.google.com/file/d/1CKuAVVHLj6oZrzccxDCDo8YsOQpYrrYO/view?usp=sharing

RARFILE

**Comment by ellensp** [comment]
Not a support forum, 

This Issue Queue is for Marlin Configuration bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/qNnSzsug
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
