### ISSUE TITLE
Current surge after Power up with M80

### ISSUE THREAD

**Issue by tphan26363** [MarlinFirmware/Configurations#78]
The M80 is use to power up .  There are 2 thing consider:
-The default value of PSU_POWERUP_DELAY =100 is too fast for some power supply to settle.  The result is the TMC driver is not initialize properly and could cause damage to TMC driver( in my case it was flying like a bullet to the end stop)
-The power.cpp need to add an additional delay after initialize the driver.  This is because some of the board is very fast causing the motor to start to move immediately after initialize and create a high surge current to the motor creating a knocking sound.  Allow some time for the current to settle before start moving the stepper.  It then can be quiet and smooth
```cpp
void Power::power_on() {
  lastPowerOn = millis();
  if (!powersupply_on) {
    PSU_PIN_ON();

    #if HAS_TRINAMIC_CONFIG
      delay(PSU_POWERUP_DELAY); // Wait for power to settle
      restore_stepper_drivers();
       delay(PSU_POWERUP_DELAY); //add a delay to make sure no surge current if it start to move instanly
    #endif
  }
```

**Comment by thinkyhead** [comment]
Thank you for pointing this out. I will have it patched in `bugfix-2.0.x` shortly with an increased delay of 250ms and the same delay after resetting the stepper drivers.
