### ISSUE TITLE
[BUG] Enabled Native USB Drive support and Enabled EEPROM hangs BTT SKR2 on startup

### ISSUE THREAD

**Issue by T-SquaredProductions** [MarlinFirmware/Configurations#783]
### Bug Description

A build with Native USB Drive Support and EEPROM settings does not compile properly when the micro SD card is put into a BTT SKR2 board.

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/9126326/Configuration.zip)

I have also added a dual extruder and a BL-Touch probe to my printer.

I will disable the USB drive support for the time being, but I would like to be able to use it in the future.

### Steps to Reproduce

1. Uncomment "#define USB_FLASH_DRIVE_SUPPORT"
2. Uncomment "#define EEPROM_SETTINGS"
3. Build the code, load it to your micro SD card, and put it into the board from an "off" state.

**Expected behavior:**

The 3D printer should start up properly, with the Marlin logo and version number.

**Actual behavior:**

The printer hangs with a blank display, no control, and no response.

**Comment by thisiskeithb** [comment]
Your config is not for the current version of Marlin and you are filing a bug in the wrong repo.

Please open a [proper ticket ](https://github.com/MarlinFirmware/Marlin/issues)once you have tried the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/refs/heads/bugfix-2.1.x.zip) and confirmed the issue still exists.
