### ISSUE TITLE
Motherboard not Defined

### ISSUE THREAD

**Issue by sotto01** [MarlinFirmware/Configurations#792]
Compiling a file for Ender 3 Pro. The Error: MOTHERBOARD is not defined in Configuration.h posts with the failure message. Using STM32F103RET6_creality environment.

**Comment by ellensp** [comment]
Not a support forum.

It means in Your Configuration.h you do not have a #define MOTHERBOARD line 

eg https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.1.x/config/examples/Creality/Ender-3%20Pro/CrealityV422/Configuration.h#L90

**Comment by sotto01** [comment]
That is the problem, the code is as it should be by all the sources I looked at. I apologize if this is the wrong place for this discussion.
