### ISSUE TITLE
[BUG] Movement issue with Artillery Genius & BL-Touch

### ISSUE THREAD

**Issue by VoOoUoOoV** [MarlinFirmware/Configurations#798]
### Bug Description

I am Using Artillery Genius (not pro edition)
If BL-Touch is on, the movement in X axe with more then 210mm is wrong because the Z axe will move up/down (TMC2100 / TMC2209) too.
Is X > 210 and i move Y axe, the Z axe is moving too. 

### Configuration Files

[Marlin2.1.1.0_Configs___C_7.zip](https://github.com/MarlinFirmware/Configurations/files/9300819/Marlin2.1.1.0_Configs___C_7.zip)

### Steps to Reproduce

* Get extruder head to x default (left position)
* Turn Printer on
* Activate BL Touch / 3D Touch (M420 S1)
* Use terminal or TFT Screen to move X axe over 210 mm
* When move Y axe (and X axe is >= 211mm), Z axe moves too

**Expected behavior:**

X axe driving normal
Y axe does not let Z axe move.

**Actual behavior:**

X axe and Z axe are driving (both at same time), if X axe > 210 mm
Y axe and Z axe are driving (both at same time), if X axe > 210 mm

#### Additional Information

The strange behavior happens with Marlin 2.0.9.3 + 2.0.9.5 + 2.1.0.0 + 2.1.1.0

**Comment by VoOoUoOoV** [comment]
I just found out, if i change @ Configuration.h the size from 220 to 230, i get the same behavior, but with an offset of 10. Therefore i changed to 240 and the rising Z axe would start at 230.
![grafik](https://user-images.githubusercontent.com/81052421/183984053-8054f198-8c40-4969-ba09-cb91bfad2cf4.png)

My max Bed Size is 230x230. But i still belive it should not happen (rising z axe)

Now i set it back to max 230, because ABL tries to get outside 230...

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by PrintSphere** [comment]
I lost my Account (the creator of this issue) and will use this new created one.

> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

I'am cooking a new build for the printer with stable 2.1.2.4 and it seems be fixed. Thank you :)
