### ISSUE TITLE
Printer stutter ( especially on curves) when abl active.

### ISSUE THREAD

**Issue by ubr7** [MarlinFirmware/Configurations#801]
### Bug Description

Printer start print after ABL (Auto bed leveling) but everything super slow like stutter especially on curves and LCD hangs up on main menu and can't do anything. Some after time if lucky or on straight lines everything became normal. 
-Marlin Build 2.1.X bugfix (fab4fb7)
-Board MKS Gen L V2.1
-Custom 3D printer (really custom literally)
-Bl Touch kit
-Dual hot-end

### Steps to Reproduce

1. Try printing with ABL and without ABL.  Without ABL, everything normal.
2. Try all different ABL types. Nothing changed.
3. Try changed firmware. Upgrade, downgrade etc. but nothing changed.
4. Suspect some kind of speed problem (data processing actually cause board is 8 bit) and disabled Continue after Power-Loss options but nothing changed.
5. Changed (disabled and enabled) CLASSIC_JERK, S_CURVE_ACCELERATION, ADAPTIVE_STEP_SMOOTHING, LIN_ADVANCE, MIN-MAX 
STEPPER VALUE (DELAY, PULSE, RATE ETC.) but nothing changed.

**Expected behavior:**

1. Slice on CURA and put to SD card
2. Start printing procedure after all heat up and zeroing
3. After ABL (G29) start printing smooth as normal.

**Actual behavior:**

1. Slice on CURA and put to SD card
2. Start printing procedure after all heat up and zeroing
3. After ABL (G29) start printing stutter and super slow.

[Configuration files.zip](https://github.com/MarlinFirmware/Configurations/files/9353225/Configuration.files.zip)

#### Additional Information

* End of the day I read similar troubles on all kinda forums and did everything in my knowledge. Thx for any advice and help guyz.
* İf anybody needs any evidence like photo or video (like crime seen) I will gladly send.  
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
Please file a proper bug report in the main MarlinFirmware repo: https://github.com/MarlinFirmware/Marlin/issues
