### ISSUE TITLE
Some settings not correct for Ender-3 v2 4.2.2 board

### ISSUE THREAD

**Issue by Ergonomicmike** [MarlinFirmware/Configurations#806]
### Bug Description

Not so much a bug, per se. Just a few incorrect values in the configuration.h file for Creality422.

#### Additional Information

In config/examples/Creality/Ender-3 V2/CrealityV422/CrealityUI/configuration.h is says:

` #define MOTHERBOARD BOARD_CREALITY_V4`

It should be

` #define MOTHERBOARD BOARD_CREALITY_V422`
  
-----------------------------------------------

The stepper motors are defined as 

```
#define X_DRIVER_TYPE TMC2208_STANDALONE
#define Y_DRIVER_TYPE TMC2208_STANDALONE
#define Z_DRIVER_TYPE TMC2208_STANDALONE

#define E0_DRIVER_TYPE TMC2208_STANDALONE
```

While this might depend on the board itself, it seems that most later 4.2.2 boards ship with the A4988'

So these values should default to 

```
#define X_DRIVER_TYPE A4988
#define Y_DRIVER_TYPE A4988
#define Z_DRIVER_TYPE A4989

#define E0_DRIVER_TYPE A4989
```

(These might self-correct when the user changes the motherboard to v422.)
--------------------------------------------------

It should probably be noted that the example configuration.h values are set with a probe in mind. So, for example, those of us doing Manual Leveling should change 

`#define NOZZLE_TO_PROBE_OFFSET { 10, 10, 0 }`

------------------------------------------------------

to 

`#define NOZZLE_TO_PROBE_OFFSET { 0, 0, 0 }`

---------------------------------------------------

**Comment by ellensp** [comment]
BOARD_CREALITY_V4  is the same as BOARD_CREALITY_V422,  the latter was added just to stop people complaining that v422 is not listed

the V422 comes with 4 different stepper driver types
You have to look at your board to determine what you have.
  #warning "Creality 4.2.2 boards come with a variety of stepper drivers. Check the board label and set the correct *_DRIVER_TYPE! (C=HR4988, E=A4988, A=TMC2208, B=TMC2209, H=TMC2225)."


If you change your probe from the default, of course you have to change probe setting!
