### ISSUE TITLE
2.1.1 is looking for .h files with config version 2.1.2 and compile fails if using old configs

### ISSUE THREAD

**Issue by clarkkent435** [MarlinFirmware/Configurations#810]
This is by design, obviously - just a note that we need to update the downloadable config libraries to have the correct version number, e.g. 
#define CONFIGURATION_H_VERSION 02010200
vice
#define CONFIGURATION_H_VERSION 02010100

in order for them to work with the current code base. Thanks.

**Comment by EvilGremlin** [comment]
no issue here, 2.1.1 release snapshot is obviously older than 2.1.x branch
