### ISSUE TITLE
controller fan not working any more

### ISSUE THREAD

**Issue by Thijsvanzwam** [MarlinFirmware/Configurations#811]
<!--

Please follow the instructions below. Failure to do so may result in your issue being closed.

### Bug Description

Controller fan, which normally started when the steppers come to action, does not start any more.
Fan is OK and always worked on my BTT SKR V2.0 rev B

I checked the config files and all setting are the same as on previous versions. 
I checked pin-files and as far as I can see, FAN2_PIN is still the same.

### Configuration Files

[files.zip](https://github.com/MarlinFirmware/Configurations/files/9585293/files.zip)

### Steps to Reproduce

Let the stepper do something, home, print, just move normally triggers the fan2 to start.

**Expected behavior:**

fan starts to run

**Actual behavior:**

all works but fan stays still

**Comment by Thijsvanzwam** [comment]
ok... so for some reason all my text disappeared... 


Again:

CONTROLLER_FAN does not work anymore on my BTT SKR V2 rev B

normally when I start a print or do anything that would have a stepper to come to action, the controller fans starts turning.
Fan is tested and working.

[files.zip](https://github.com/MarlinFirmware/Configurations/files/9585317/files.zip)

I checked the old config files and compared them tot the new ones, CONTROLLER_FAN section is the same.
Checked the pins file and also, FAN2_PIN looks the same.

I must be missing something or there is something wrong...

expected behavior:

Let the steppers move and the fan kicks in.

actual behavior:

when steppers move, fan does nothing.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
