### ISSUE TITLE
UNABLE TO FLASH OUT OF MARLIN 2.1.1

### ISSUE THREAD

**Issue by Double077** [MarlinFirmware/Configurations#821]
I flashed successfully  to marlin 2.1.1 but after noticing some bugs with my printer decided to revert to the original firmware but never could it seems like the machine is skipping the boot loader not sure what to do. 

used this config with the ender 3 s1 pro (f4 chip)
[config.zip](https://github.com/MarlinFirmware/Configurations/files/9690418/config.zip)

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
