### ISSUE TITLE
[BUG] Creality V422 not building on release 2.1.1

### ISSUE THREAD

**Issue by alf1e** [MarlinFirmware/Configurations#825]
### Bug Description

Fails to build for creality V422 complaing version 2.1.1 config files are out of date for marlin 2.1.1

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/9741289/Configuration.zip)

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Copy and paste marlin config files into marlin 2.1.1
2. enable BLTouch in Configuration.h
3. build under any build option 

**Expected behavior:**

Compile successfully 

**Actual behavior:**

Complains that files are wrong version for this marlin
#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by EvilGremlin** [comment]
because you downloaded Marlin 2.1.x branch, which is not 2.1.1

**Comment by alf1e** [comment]
> because you downloaded Marlin 2.1.x branch, which is not 2.1.1

It says in the auto builder that it's marlin version 2.1.1

**Comment by EvilGremlin** [comment]
exact download links?

**Comment by alf1e** [comment]
> exact download links?

Not at computer right now so don't have them but when I get back should I try downloading the 2.1.1 zip file?

**Comment by EvilGremlin** [comment]
Aactually, it might say 2.1.1 in ABM, even though config version was bumped up. Anyway - error is right, this is not a bug.

**Comment by alf1e** [comment]
> Aactually, it might say 2.1.1 in ABM, even though config version was bumped up. Anyway - error is right, this is not a bug.

Oh ok sorry
