### ISSUE TITLE
[BUG] Can't Flash Tronxy X5SA Pro v6

### ISSUE THREAD

**Issue by Dtcreation** [MarlinFirmware/Configurations#829]
### Bug Description

Nothing happens when i put the update.cdb on the SD Card

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

Here files from Tronxy with the "official" build marlin firmware

**Expected behavior:**

Flash the board

**Actual behavior:**

Nothing

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.
[Configuration_adv.zip](https://github.com/MarlinFirmware/Configurations/files/9800892/Configuration_adv.zip)
[X5SAPro-446+Titan.zip](https://github.com/MarlinFirmware/Configurations/files/9800919/X5SAPro-446%2BTitan.zip)

**Comment by thisiskeithb** [comment]
Please file a proper bug report in the main Marlin repository: https://github.com/MarlinFirmware/Marlin/issues/new/choose
