### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by edergermanio1980** [MarlinFirmware/Configurations#839]
There was an error compiling the firmware for the SKR 1.4 Turbo board the command executed was:

source .venv/bin/activate
sudo src/core/config-for-machine V1CNC_SkrTurbo_2209
sudo src/core/build-for-machine

![image](https://user-images.githubusercontent.com/66970649/200669498-af0fb96a-1a0c-4586-bf82-c679feae7135.png)

To compile I'm using Windows WSL2 emulating Ubuntu

In file included from Marlin/src/feature/../inc/MarlinConfigPre.h:39,
                 from Marlin/src/feature/../inc/MarlinConfig.h:28,
                 from Marlin/src/feature/spindle_laser.cpp:27:
Marlin/src/feature/../inc/../../Configuration.h:1:31: error: 'PC9' was not declared in this scope
    1 | #define SPINDLE_LASER_PWM_PIN PC9
      |                               ^~~
Marlin/src/feature/spindle_laser.cpp:82:28: note: in expansion of macro 'SPINDLE_LASER_PWM_PIN'
   82 |     hal.set_pwm_duty(pin_t(SPINDLE_LASER_PWM_PIN), SPINDLE_LASER_PWM_OFF); // Set to lowest speed
      |                            ^~~~~~~~~~~~~~~~~~~~~
Marlin/src/feature/spindle_laser.cpp: In static member function 'static void SpindleLaser::_set_ocr(uint8_t)':
Marlin/src/feature/../inc/../../Configuration.h:1:31: error: 'PC9' was not declared in this scope
    1 | #define SPINDLE_LASER_PWM_PIN PC9
      |                               ^~~
Marlin/src/feature/spindle_laser.cpp:103:28: note: in expansion of macro 'SPINDLE_LASER_PWM_PIN'
  103 |     hal.set_pwm_duty(pin_t(SPINDLE_LASER_PWM_PIN), ocr ^ SPINDLE_LASER_PWM_OFF);
      |                            ^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/LPC1769/src/src/feature/spindle_laser.cpp.o] Error 1
In file included from Marlin/src/gcode/calibrate/../../inc/../pins/pins.h:917,
                 from Marlin/src/gcode/calibrate/../../inc/MarlinConfig.h:34,
                 from Marlin/src/gcode/calibrate/G28.cpp:23:
Marlin/src/gcode/calibrate/../../inc/../pins/pins_postprocess.h:540: warning: "Z_MIN_PIN" redefined
  540 |       #define Z_MIN_PIN Z_STOP_PIN
      |
In file included from Marlin/src/gcode/calibrate/../../inc/MarlinConfigPre.h:39,
                 from Marlin/src/gcode/calibrate/../../inc/MarlinConfig.h:28,
                 from Marlin/src/gcode/calibrate/G28.cpp:23:
Marlin/src/gcode/calibrate/../../inc/../../Configuration.h:3363: note: this is the location of the previous definition
 3363 | #define Z_MIN_PIN P1_27
      |
===================================================================== [FAILED] Took 54.65 seconds =====================================================================

Environment    Status    Duration
-------------  --------  ------------
LPC1769        FAILED    00:00:54.649
------------------------------------------------------------------------------------------------------------------------
The file  V1CNC_SkrTurbo_2209 content:

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_turbo_1p4
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser

export PLATFORMIO_ENV=LPC1769

**Comment by thisiskeithb** [comment]
You'll need to file a bug with [V1 Engineering](https://github.com/V1EngineeringInc/MarlinBuilder) since we can't support forks of Marlin here.
