### ISSUE TITLE
Fatal error in /Marlin/SRC/Hal/LPC1768/HAL_SPI.cpp line 216 (PlatformIO)

### ISSUE THREAD

**Issue by TScriptDoc** [MarlinFirmware/Configurations#84]
Hi everyone, I hope all of you are fine!

I had some trouble last night trying to compile marlin bugfix-2.0.x, because of a fatal error in /Marlin/SRC/Hal/LPC1768/HAL_SPI.cpp line 216 (PlatformIO - 'void SPIClass::beginTransaction(SPISettings)' does not match any in class 'SPIClass'). So, I figured out that in Marlin/HAL/LPC1768/incluse/spi.h, line 42 was "void beginTransaction(const SPISettings&);". So I reverted spi.h line 42 to "void beginTransaction(SPISettings);" as in Marlin-2.0.0.0 and it compiled fine. Is it ok?

**Comment by thinkyhead** [comment]
Issue resolved.
