### ISSUE TITLE
[BUG] In MotherBoard Creality v2.2/Does anyone know how I can put the original Firmware?

### ISSUE THREAD

**Issue by Yurumakum** [MarlinFirmware/Configurations#848]
I recently replaced the board of my 3d printer for a Motherboard - Creality v2.2, my Firmware (Version 2.1) is inverging the X and Y axes, when a command is given to the Y axis, which responds turns out to be the X (The same error occurs in an equivalent way if the command is for the X axis), i tried from version 2.0.9.5 up to 2.1.1, however I had no success in any of them.

Can someone help me?

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server
