### ISSUE TITLE
Ender7

### ISSUE THREAD

**Issue by tcs320** [MarlinFirmware/Configurations#861]
Hi, 

I searched every where and I can't find any replacement Firmware for the Ender 7.
Will there be an Marlin Configuration coming for the Ender 7 or is Creality blocking that somehow because nobody is developing Firmware.

I bought a new Spider Hotend and just need to adjust the MAX Temp in the Firmware.
Does anyone have information about that?

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/649
