### ISSUE TITLE
[BUG] Typo in Cofig_adv for B1 SE

### ISSUE THREAD

**Issue by vovodroid** [MarlinFirmware/Configurations#862]
//#define PROBING_MARGIN_LEFT PROBING_MARGIN
  //#define PROBING_MARGIN_RIGHT PROBING_MARGIN
  //#define PROBING_MARGIN_FRONT PROBING_MARGIN
  //#define **PROBING_MARGIN_FRONT** PROBING_MARGIN

https://github.com/MarlinFirmware/Configurations/blob/import-2.1.x/config/examples/BIQU/B1%20SE/Configuration_adv.h#L2192

Should be PROBING_MARGIN_BACK, shouldn't it?

**Comment by ellensp** [comment]
Yes it should

**Comment by ellensp** [comment]
A PR to correct this has been created,
