### ISSUE TITLE
Ender 3 Pro XY printable area too large

### ISSUE THREAD

**Issue by scrith** [MarlinFirmware/Configurations#866]
The printable area for the Ender 3 Pro is 220 x 220 x 250. This is according to the official Creality data sheet. https://www.creality.com/products/ender-3-pro-3d-printer

The example files incorrectly list 235 x 235 as the printable XY area

**Comment by thisiskeithb** [comment]
Creality's info is not correct. The nozzle can reach the entire 235mm build area on the Ender-3 & Pro models, so that's why they are listed that way.
