### ISSUE TITLE
[BUG] Configuration for BQ hephestos 2 not working (version 2.1.1)

### ISSUE THREAD

**Issue by Cavalletta98** [MarlinFirmware/Configurations#868]
Hi, i flashed the marlin fw version 2.1.1 with the corellated configuration files present in this repo and the printer is not working as expected. In particular, if i start a print, the layers of the object are not printed one of top the other. Every layer, the printer prints outside of the object causing a not vertical object ( sometimes the printer prints outside the area of the object)
I don't know if there is something that i have to change in the configuration or is some fw problem. In the image you can see some examples. If could be fw problem, i will post on the other repo, thanks
[IMG_20221226_183349.jpg](https://user-images.githubusercontent.com/45316566/209707539-64b05b1b-eea5-4ed5-8a1b-4e947c120c10.jpg)![IMG_20221226_162004.jpg](https://user-images.githubusercontent.com/45316566/209707580-857fd63d-bdbb-4596-bff6-4e57f125d4ad.jpg)![IMG_20221226_183349.jpg](https://user-images.githubusercontent.com/45316566/209707812-a09a2f39-a0ed-4153-99dc-75e6330d53d2.jpg)

**Comment by thisiskeithb** [comment]
Closing since you've opened a Pull Request:
- https://github.com/MarlinFirmware/Configurations/pull/869
