### ISSUE TITLE
want to move X Y and Z axis  in both negative and and positive direction.. 

### ISSUE THREAD

**Issue by Ramr93** [MarlinFirmware/Configurations#878]
want to move X Y and Z axis  in both negative and and positive direction..  on moving axis direction  menu> motion> move axis > z axis 
the value goes only zero. i want to move below  zero (negative value). how will i do it ?
ref : https://www.youtube.com/watch?v=jlOyqca9AqM&t=1s&ab_channel=LinhkienTCM

**Comment by ellensp** [comment]
This Issue Queue is for Marlin Configuration bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
