### ISSUE TITLE
In JG Aurora A1 and A5S advanced configs,  FAN_ACTIVE_STATE LOW should be FAN_INVERTING 1

### ISSUE THREAD

**Issue by CFTBL** [MarlinFirmware/Configurations#908]
The example Configuration_adv.h for JG Aurora A1 and A5S contains the following line:

#define FAN_ACTIVE_STATE LOW

FAN_ACTIVE_STATE isn't implemented. It must be replaced with:

#define FAN_INVERTING 1

...otherwise the part cooling fan will react opposite the way it should (for example, M106 will turn it off, M107 will turn it on).

This error showed up in the JG Aurora A1/A5S example configuration for release 2.0.9.3 and all releases since then, up to and including the current 2.1.x bugfix examples.

It appears in the 2.0.9.4 Example Configuration README, under Changes,  as...

FAN_INVERTING => FAN_ACTIVE_STATE (LOW)

**Comment by CFTBL** [comment]
I went ahead and submitted a pull request, #909, to fix this.

**Comment by thisiskeithb** [comment]
Closing since you've opened a PR.
