### ISSUE TITLE
import-2.0.x versus bugfix-2.0.x? 

### ISSUE THREAD

**Issue by swilkens** [MarlinFirmware/Configurations#91]
**Question:**
The readme in the marlin firmware for the `bugfix-2.0.x` firmware branch notes we shoud use the `bugfix-2.0.x` branch of the configuration files as well.

That's all well and good, but the configurations repository defaults to the `import-2.0.x` branch. On top of this, the `bugfix-2.0.x` branch is currently 101 commits **behind** the default `import-2.0.x` branch.

Which should we be using now? What is the goal of the `import-2.0.x` branch? 

![image](https://user-images.githubusercontent.com/13329383/81085262-47bf3100-8ef7-11ea-9261-dc33327c299c.png)

**Comment by thinkyhead** [comment]
Only the import branches are edited by humans. The rest are generated by a script.
