### ISSUE TITLE
Bed Tramming Labels are Incorrect [BUG] (bug summary)

### ISSUE THREAD

**Issue by akinilicali** [MarlinFirmware/Configurations#915]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

CONFIGURATION_H_VERSION 02010300 (Bugfix 2.1.x)
LCD Bed Tramming Wizard labels are incorrect.
They are listed in this order:
Front Left
Back Left
Back Right
Front Right
They actually move in this order (when above is followed)
Front Left
Front Right
Back Right
Back Left

### Bug Timeline

Current 'Nightly' Bugfix 2.1.x

### Expected behavior

I expected the print head to move in line with the screen prompts.

### Actual behavior

It did not move like that instead it followed the order detailed in the Bug Details section.

### Steps to Reproduce

CR-10 S5 printer.
Turn on
Select Tramming Wizard from the LCD menu

### Version of Marlin Firmware

2.1.X Bugfix

### Printer model

Creality CR10 S5

### Electronics

Newly upgraded to BTT SKR E3 V3 mainboard. 

### Add-ons

None 

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/11115985/Marlin.zip)

**Comment by lukasradek** [comment]
This is a configuration issue not a Marlin firmware issue.
Not sure where you got that config from but in Configuration_adv.h, there is the following:

```
#define TRAMMING_POINT_XY { {  85, 85 }, { 415, 85 }, { 415, 415 }, { 85, 415 } } // CR-10 S5 config

// Define position names for probe points. // CR-10 S5 config
#define TRAMMING_POINT_NAME_1 "Front-Left"
#define TRAMMING_POINT_NAME_2 "Back-Left"
#define TRAMMING_POINT_NAME_3 "Back-Right"
#define TRAMMING_POINT_NAME_4 "Front-Right"
```

The first line defines the tramming points in XY coordinate pairs - first is X, second Y.
The following lines define names for the points, where the X in the TRAMMING_POINT_NAME_X referes to the order, they were defined in the first line.

If you printer has home position (x0,y0) at front left (as most do), you can see that Front-Left is x85y85, which is correct but after that the points are misplaced. x415y85 should be Front-Right and so on.

You can change it yourself and if that config was supplied from somewhere, you can notify the creator.

**Comment by thisiskeithb** [comment]
This will be fixed in https://github.com/MarlinFirmware/Configurations/pull/914
