### ISSUE TITLE
[BUG] Ultimaker 2 - Encoder Steps wrong

### ISSUE THREAD

**Issue by kallisti5** [MarlinFirmware/Configurations#918]
### Bug Description

The ENCODER_PULSES_PER_STEP 1 is incorrect for the Ultimaker 2.  The encoder requires ```ENCODER_PULSES_PER_STEP 2``` otherwise, the on-screen cursor moves multiple steps for one encoder step.

Branch:  bugfix-2.1.x

**Comment by thisiskeithb** [comment]
Thanks for the report! Fixed in https://github.com/MarlinFirmware/Configurations/pull/925
