### ISSUE TITLE
Creality Ender 3 (not the V2) has #define DWIN_ENDER3_V2 enabled

### ISSUE THREAD

**Issue by swilkens** [MarlinFirmware/Configurations#92]
**Issue:**
Standard Ender 3 **(V1)** configuration file has the DWIN display type enabled, but the V1 of this printer doesn't have this display type - only the V2 does.

Line 2092 in Configuration.h from the `bugfix-2.0.x` branch:
`#define DWIN_ENDER3_V2`

Probably should be:
`//#define DWIN_ENDER3_V2`

It seems this is already fixed in the `import-2.0.x` branch:
https://github.com/MarlinFirmware/Configurations/blob/import-2.0.x/config/examples/Creality/Ender-3/Configuration.h#L2092

**Comment by thinkyhead** [comment]
The bugfix branch is just a rebuilt version of the import branch. If something isn't in bugfix at the moment, it will appear as soon as the branch is rebuilt in sync with the import branch.

**Comment by swilkens** [comment]
This happens rapidly then? As currently, the config in the bugfix branch is invalid for this printer.

**Comment by thinkyhead** [comment]
Typically within 24-48 hours of recent updates, depending on workload and life events.

**Comment by swilkens** [comment]
Apologies, I misunderstood your earlier reply. Thank you for the clarification, and thanks for all your efforts in this project.
