### ISSUE TITLE
Difference between `Ender-3` and `Ender-3 Pro` configurations?

### ISSUE THREAD

**Issue by qwertychouskie** [MarlinFirmware/Configurations#923]
When comparing the configs for the Ender 3 and Ender 3 Pro for the Creality 4.2.7 board, other than the expected name differences, I noticed that `Z_STEPPER_ALIGN_ITERATIONS` is set to `3` for the Ender 3 and `5` for the Ender 3 Pro.  Was this an intentional change?  If so, what does it affect?  Thanks.

**Comment by thisiskeithb** [comment]
It could have been on accident or just the preference of the person submitting the config. I've submitted https://github.com/MarlinFirmware/Configurations/pull/928 to unify `Z_STEPPER_ALIGN_ITERATIONS` across all Ender-3 & Ender-3 Pro configs to the default value of 5.
