### ISSUE TITLE
z z2 endstop  reversed

### ISSUE THREAD

**Issue by microsoul** [MarlinFirmware/Configurations#930]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

endstops z is reversed they are in the opposite stepper

### Bug Timeline

new

### Version of Marlin Firmware

2.1.2

### Printer model

anycubic i3 mega

### Electronics

trigorilla stock

### Add-ons

no

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11359564/Configuration.zip)

**Comment by rondlh** [comment]
Did you see the comment in Configuration.h, line 161?

```
/**
 * Some Anycubic machines have Z1 and Z2 swapped to save on wiring.
 */
//#define SWAP_Z_MOTORS
```
