### ISSUE TITLE
[BUG] Ender 5 w/ BL Touch - HOMING FAILED, PRINTER HALTED, Please reset -  bugfix-2.1.x only

### ISSUE THREAD

**Issue by ghost** [MarlinFirmware/Configurations#947]
### Bug Description

When using version bugfix-2.1.0, as I auto home on an Ender 5 printer with a BL Touch, I encounter an error "HOMING FAILED, PRINTER HALTED, Please reset". Even though everything went well (motor stops after encountering probe).

### Configuration Files
DEFAULT_ENV : STM32F103RE_creality
[confs.zip](https://github.com/MarlinFirmware/Configurations/files/11665660/confs.zip)

### Steps to Reproduce

BL Touch is wired using the 5 to 5 pin connector, so no possible wiring mistake.
BL Touch is genuine from Creality, not a clone.

If I use bugfix-2.0.0, everything works fine with the exact same changes (wished I tried sooner 🥲). 

Relevant configuration changes : 
Creality Ender 5 - V427 preset

 #define USE_PROBE_FOR_Z_HOMING
 //#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define BLTOUCH
#define NOZZLE_TO_PROBE_OFFSET { -44, -9, 0 } For Use with Stock BL Touch Brackets
#define AUTO_BED_LEVELING_BILINEAR
#define Z_SAFE_HOMING

 #define BLTOUCH_DELAY 500
 #define BLTOUCH_FORCE_SW_MOD

What I tried : 
* Plugged or Unplugged zstop sensor -> nothing changed (I updated Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN as I made these tests)

**Expected behavior:**
The error should just not appear as everything went well.

**Actual behavior:**
Error displays and I cannot print anything.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by ghost** [comment]
Hello, 
I figured out that this screen only pops when I manually trigger the bltouch probe as part of the homing process. I guess the firmware did not recognize it as a standard hit and more as a physical obstruction, if that makes sense.
That was it. 

And thanks, I will know for the next time.
