### ISSUE TITLE
Creality CR10s v1 has a microSD card extender.   #define NO_SD_DETECT must be enabled by default.

### ISSUE THREAD

**Issue by isidorosss** [MarlinFirmware/Configurations#953]
[Configuration.zip](https://github.com/MarlinFirmware/Configurations/files/11782017/Configuration.zip)

Hello to all. My Creality CR10s v1 has an SDcard extender. So the microSD card isn't recognised unless i enable on Configuration_adv.h , line 1743:
#define NO_SD_DETECT

Can somebody else with this printer confirm it? It can't be only my printer. Then we can have it enabled by default on future releases.

**Comment by EvilGremlin** [comment]
This is the case with all extenders.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
