### ISSUE TITLE
[BUG] EZ31865 + PT100 + BTT OCTOPUS MAX EZ V1.0 + H2O

### ISSUE THREAD

**Issue by gianguardo** [MarlinFirmware/Configurations#954]
Hello, I'm trying to configure EZ31865 for Octopus max ez but I receive from the display ERR Max Temp E1 or ERR Min Temp E1. Can someone help me?

My setup:
Configuration.h
#define TEMP_SENSOR_0   -5
#define MAX31865_SENSOR_OHMS_0              100 
#define MAX31865_CALIBRATION_OHMS_0      430
#define HEATER_0_MAXTEMP 520

Pin_BTT_OCTOPUS_MAX_EZ.h
/*
#define E1_STEP_PIN                          PG15 // MOTOR 6
#define E1_DIR_PIN                            PB3
#define E1_ENABLE_PIN                     PD5
#ifndef E1_CS_PIN
  #define E1_CS_PIN                           PG9
#endif
*/
//MAX31865 MnP
#define TEMP_0_MISO_PIN               PE13
#define TEMP_0_SCK_PIN                  PE12
#define TEMP_0_MOSI_PIN               PE14
#define TEMP_0_CS_PIN                   PG9

I also tried enabling in Configuration_adv.h , no results
#define TEMP_SENSOR_FORCE_HW_SPI       
 
I also tried to follow the instructions of the Biqu but nothing     

Thank you and good day

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
