### ISSUE TITLE
[BUG] EZ31865 + PT100 + BTT OCTOPUS MAX EZ  

### ISSUE THREAD

**Issue by gianguardo** [MarlinFirmware/Configurations#955]
Hello, I'm trying to configure EZ31865 for Octopus max ez but I receive from the display err 989 as room temperature .
(I tried in the forum but no one has solved the problem)

My setup:
Configuration.h
#define TEMP_SENSOR_0 -5
#define MAX31865_SENSOR_OHMS_0 100
#define MAX31865_CALIBRATION_OHMS_0 430
#define HEATER_0_MAXTEMP 520

Pin_BTT_OCTOPUS_MAX_EZ.h
/*
#define E1_STEP_PIN PG15 // MOTOR 6
#define E1_DIR_PIN PB3
#define E1_ENABLE_PIN PD5
#ifndef E1_CS_PIN
#define E1_CS_PIN PG9
#endif
*/
//MAX31865 MnP
#define TEMP_0_MISO_PIN PE13
#define TEMP_0_SCK_PIN PE12
#define TEMP_0_MOSI_PIN PE14
#define TEMP_0_CS_PIN PG9

Configuration_adv.h 
//#define TEMP_SENSOR_FORCE_HW_SPI

#define IGNORE_THERMOCOUPLE_ERRORS but i get er 989 as room temperature

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Configurations/issues/954
