### ISSUE TITLE
[BUG] Non symmetrical bed callibration mesh for Ender 3 with BLTOUCH

### ISSUE THREAD

**Issue by TzOk83** [MarlinFirmware/Configurations#969]
Right probing points are offset towards the center of the bed, due to the probe offset to the left of the head (for the probe to touch the right edge of the bed, the head would need to be over 40 mm aside from the bed's edge). The issue exists "since always", and is still present in v.2.1.2.1. The minimal mesh margin (PROBING_MARGIN) for the mesh to be symmetrical is 35 mm.

Probe offsets (NOZZLE_TO_PROBE_OFFSET) for Ender 3 are:  -42, -6.5, -3.9.

**Comment by thisiskeithb** [comment]
`NOZZLE_TO_PROBE_OFFSET` depends entirely on the type & location of the mount you're using, so you'll need to tune your own offsets.

**Comment by TzOk83** [comment]
There are official metal mounts for the BLTOUCH for Creality printers, so there's nothing against using their dimensions as the default values in appropriate configuration files. Only Z-offset may require manual tuning. The main issue is with the symmetricity of the mesh, either the configuration should allow moving the head outside the bed (there is plenty of rail there), or the default margin should be far more than 10 mm.

**Comment by thisiskeithb** [comment]
> There are official metal mounts for the BLTOUCH for Creality printers, so there's nothing against using their dimensions as the default values in appropriate configuration files.

Sure, but some configs have readmes that point to the mounts used (which aren't from Creality). Your config will likely need tweaking based on your particular machine.
