### ISSUE TITLE
[BUG] Ender 5 plus with Dwin Set not working

### ISSUE THREAD

**Issue by leseaw** [MarlinFirmware/Configurations#971]
## Bug Description

First LCD flashed, also worked end line came. New design is also on it.

After that Marlin flashed, no function. I can press LCD and new windows go up but nothing moves. No temperature control, nothing happens.

## Configuration Files

From `Configurations/bugfix-2.1.x`

## Steps to Reproduce

- Update LCD to use `DGUS_LCD_UI RELOADED` the stock LCD must be flashed with custom firmware.

### Get the `DWIN_SET`

- Download the `DWIN_SET` archive from https://github.com/MarlinFirmware/Configurations/raw/bugfix-2.1.x/config/examples/Creality/Ender-5%20Plus/DGUS-Reloaded/DWIN_SET.tar.gz
- Extract the contents of the archive. You should now have a folder called `DWIN_SET`.

    Compile Firmware with VS Code
    Upload .hex File with Prusa Sclicer
    Start Printer, nothing is moving or heating

Expected behavior:

Printer prints

Actual behavior:

Printer only show LCD Dektop, Can select everything but then nothing happens

Edit: Addendum, I can move axes via Repetierhost, so firmware seems to work

I have followed the instructions that come with it.
Everything was done as it should [be.]

**Comment by leseaw** [comment]
---

**Comment by thinkyhead** [comment]
For future reference and future visitors to this issue…. With `DGUS_LCD_UI RELOADED` you must use the `DWIN_SET` from https://github.com/Neo2003/DGUS-reloaded/releases
