### ISSUE TITLE
External drivers in marlin firmware 2.1.2.1

### ISSUE THREAD

**Issue by johnstephansen** [MarlinFirmware/Configurations#974]
Hello

I use Marlin firmware 2.1.2.1. motherboard: Octopus pro V1.1 (H723)
Bigtreetech.

Printer: Cartesian - x-axis with ribbon - y-axis with ribbon, both with nema 23 closed stepper motor and both axes with separate motor and stepper driver Cl1-507.
The Z axis is driven by 4 spindles, each with its own motor, they are connected in 2 series, each series with its own driver: MKS TB6600 v1.1 2014.
E axis 1 extruder A4988.

X Y and Z run on power around the motherboard.

I have purchased 4 pieces: Description:
3D Printer Motor Drive Converter Adapter Converter Expansion Adapter for Big 57 86 Motors.
Package includes:
6 x 3D printer motor drive converter adapter boards (3D printer motherboard not included).
6 x 6-pin connection cable

For mounting in the motherboard.

Questions:
1) How to setup this in marlin firmware. it is not possible to add above drivers in configaration.h.? Should one then choose one of the possible drivers, for example A4988.?

2) In configaration adv.h, Line 2329 Can a new minimum delay be set, and if you choose this it is then possible to link these to the 2 different external drivers with different values, corresponding to the needs of the 2 drivers.?

Hope someone can answer my questions, it will be a great help.

John Stephansen(Redigeret)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
