### ISSUE TITLE
[BUG] (ENCODER not work) 

### ISSUE THREAD

**Issue by APToni** [MarlinFirmware/Configurations#976]
Hi. I tried to update my old board BOARD_MKS_GEN_L_V21 with LCD REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER previously removed from the Tevo Tornado printer, but after the update on Marlin 2.1.2.1 the encoder stopped working.

Use Visual Studio Code
Version: 1.83.0 (user setup)
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

1. I downloaded two versions from the site 2.1.2.1 and 2.0.9.7 LTS.
2. In 2.1.2.1 changed 
#define MOTHERBOARD BOARD_MKS_GEN_L_V21 (changed board name)
#define NO_LCD_MENUS (uncommented)
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER (uncommented)
When flashing the firmware, the inscription is displayed but the encoder does not work.
3. Turned the connector 2, 180 degrees, not help. Encoder does not work.
4. I found the contacts on the display board for the encoder, which is responsible for pressing the button, I closed them, it did not help.
5. In 2.0.9.7 LTS changed
#define MOTHERBOARD BOARD_MKS_GEN_L_V21 (changed board name)
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER (uncommented)
BUT #define NO_LCD_MENUS not found in LTS version.
6. When flashing the firmware 2.0.9.7 LTS, the inscription is displayed but the encoder work. Everything works fine.

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
