### ISSUE TITLE
[BUG] JGAURORA MAGIC - Encoder is inverted

### ISSUE THREAD

**Issue by nvdias0** [MarlinFirmware/Configurations#978]
In configuration.h 
#define REVERSE_ENCODER_DIRECTION

shold be activated. (uncommented)

**Comment by thisiskeithb** [comment]
[According to the stock config](https://github.com/JGMaker3dofficial/magic/blob/cf104ef6cbe44f9e12dc0b17975241ff191c9c9f/magic/Marlin/Configuration.h#L1481-L1486), it appears we should update the config here.

```cpp
//
// This option reverses the encoder direction everywhere.
//
//  Set this option if CLOCKWISE causes values to DECREASE
//
#define REVERSE_ENCODER_DIRECTION
```

**Comment by thisiskeithb** [comment]
Thanks for the report! This will be fixed in https://github.com/MarlinFirmware/Configurations/pull/980
