### ISSUE TITLE
Ender 3 S1 Pro ,LED bar not powered

### ISSUE THREAD

**Issue by VAGNERT70** [MarlinFirmware/Configurations#983]
I made a short circuit on the 2 wires of the LED bar, and the 24V no longer reaches the connector. the rest of the 3d printer works perfectly. the 24v voltage for the leds comes from the mainbord. How can I do? Thank you
Ender 3 S1 Pro

**Comment by EvilGremlin** [comment]
Waaaay offtopic.
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

* MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
* RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
* Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
* Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
* [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
* 3D Printing Discord server. Join link: https://discord.gg/3dprinters
* Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a bug report.
