### ISSUE TITLE
fysect e4 esp32 TMC2209 UART driver error

### ISSUE THREAD

**Issue by yoroboticscolombia** [MarlinFirmware/Configurations#991]
Hi, Im trying to configure the board and change the driver current, but i tried setting monitor driver status, but i get this message:

18:58:52.344 : E (5870) uart: uart_get_buffered_data_len(1342): uart driver error

![image](https://github.com/MarlinFirmware/Configurations/assets/62781222/150d5d80-270a-45aa-b11f-4a86e03d6fd3)
![image](https://github.com/MarlinFirmware/Configurations/assets/62781222/55f9bd24-f1e2-4f33-895b-2f707359bdde)

what can be causing this.
I have already knowledge of marlin and esp3d.

thanks.

**Comment by thisiskeithb** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by yoroboticscolombia** [comment]
THanks
